//
//  Categorias.swift
//  True Dare or shots
//
//  Created by Joel Lozano on 02/10/18.
//  Copyright © 2018 diego. All rights reserved.
//

import Foundation

class CategoriasVerdad{
    
    
    enum categories {
        case Verdad
        case Reto
        case Shot
    }
    
    enum subcategori{
        case Inocentes
        case Amigables
        case Sexuales
        case Prohibidas
    }
    var categoria :categories
    var subCategoria: subcategori
    var preguntas = [Preguntas]()
    
    init() {
        categoria = .Verdad
        subCategoria = .Inocentes
        // preguntas verdad inocentes
        let p1 = Preguntas.init(id: 1, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "Si fueras un alimento ¿Qué serías y ¿cómo otras personas te comerían?")
        let p2 = Preguntas.init(id: 2, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "¿Con qué tipo de persona te gustaría casarte algún dia?")
        let p3 = Preguntas.init(id: 3, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "¿Cuál es tu talento secreto?")
        let p4 = Preguntas.init(id: 4, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "¿Si tuvieras la oportunidad de volver a nacer como alguien más en este cuarto,¿quién sería?¿Por qué?" )
        let p5 = Preguntas.init(id: 5, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "Si le va a dar consejo de (no hagas lo que yo hice) a una persona mas joven ¿qué sería?" )
        let p6 = Preguntas.init(id: 6, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "¿Cuál es tu idea de una cita perfecta?" )
        let p7 = Preguntas.init(id: 7, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "¿Alguna vez has besado al hermano o hermana de un amigo?" )
        let p8 = Preguntas.init(id: 8, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "¿Cuándo has amado a alguien que no te haya amado de vuelta?")
        let p9 = Preguntas.init(id: 9, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "¿Cuando tuviste tu primer beso y cómo fue?" )
        let p10 = Preguntas.init(id: 10, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"¿De que tienes miedo?" )
        let p11 = Preguntas.init(id: 11, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "¿Cuál es tu mayor secreto?")
        let p12 = Preguntas.init(id: 12, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "Si pudieras cambiar una cosa en tu cuerpo, ¿cuál sería?" )
        let p13 = Preguntas.init(id: 13, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "Si tuvieras la oportunidad de salir en una cita con alguien que está presente, ¿quién sería?" )
        let p14 = Preguntas.init(id: 14, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p15 = Preguntas.init(id: 15, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p16 = Preguntas.init(id: 16, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p17 = Preguntas.init(id: 17, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p18 = Preguntas.init(id: 18, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p19 = Preguntas.init(id: 19, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p20 = Preguntas.init(id: 20, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p21 = Preguntas.init(id: 21, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p22 = Preguntas.init(id: 22, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p23 = Preguntas.init(id: 23, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"" )
        let p24 = Preguntas.init(id: 24, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "")
        let p25 = Preguntas.init(id: 25, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p26 = Preguntas.init(id: 26, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p27 = Preguntas.init(id: 27, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p28 = Preguntas.init(id: 28, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p29 = Preguntas.init(id: 29, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p30 = Preguntas.init(id: 30, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p31 = Preguntas.init(id: 31, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p32 = Preguntas.init(id: 32, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p33 = Preguntas.init(id: 33, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p34 = Preguntas.init(id: 34, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p35 = Preguntas.init(id: 35, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p36 = Preguntas.init(id: 36, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"" )
        let p37 = Preguntas.init(id: 37, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "")
        let p38 = Preguntas.init(id: 38, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p39 = Preguntas.init(id: 39, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p40 = Preguntas.init(id: 40, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p41 = Preguntas.init(id: 41, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p42 = Preguntas.init(id: 42, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p43 = Preguntas.init(id: 43, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p44 = Preguntas.init(id: 44, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p45 = Preguntas.init(id: 45, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p46 = Preguntas.init(id: 46, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p47 = Preguntas.init(id: 47, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p48 = Preguntas.init(id: 48, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p49 = Preguntas.init(id: 49, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"" )
        let p50 = Preguntas.init(id: 50, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "")
        let p51 = Preguntas.init(id: 51, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p52 = Preguntas.init(id: 52, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p53 = Preguntas.init(id: 53, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p54 = Preguntas.init(id: 54, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p55 = Preguntas.init(id: 55, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p56 = Preguntas.init(id: 56, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p57 = Preguntas.init(id: 57, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p58 = Preguntas.init(id: 58, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p59 = Preguntas.init(id: 59, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p60 = Preguntas.init(id: 60, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p61 = Preguntas.init(id: 61, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p62 = Preguntas.init(id: 62, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"" )
        let p63 = Preguntas.init(id: 63, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "")
        let p64 = Preguntas.init(id: 64, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p65 = Preguntas.init(id: 65, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p66 = Preguntas.init(id: 66, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p67 = Preguntas.init(id: 67, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p68 = Preguntas.init(id: 68, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p69 = Preguntas.init(id: 69, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p70 = Preguntas.init(id: 70, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p71 = Preguntas.init(id: 71, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p72 = Preguntas.init(id: 72, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p73 = Preguntas.init(id: 73, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p74 = Preguntas.init(id: 74, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p75 = Preguntas.init(id: 75, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"" )
        let p76 = Preguntas.init(id: 76, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "")
        let p77 = Preguntas.init(id: 77, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p78 = Preguntas.init(id: 78, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p79 = Preguntas.init(id: 79, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p80 = Preguntas.init(id: 80, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p81 = Preguntas.init(id: 81, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p82 = Preguntas.init(id: 82, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p83 = Preguntas.init(id: 83, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p84 = Preguntas.init(id: 84, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p85 = Preguntas.init(id: 85, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p86 = Preguntas.init(id: 86, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p87 = Preguntas.init(id: 87, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p88 = Preguntas.init(id: 88, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"" )
        let p89 = Preguntas.init(id: 89, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "")
        let p90 = Preguntas.init(id: 90, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p91 = Preguntas.init(id: 91, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p92 = Preguntas.init(id: 92, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p93 = Preguntas.init(id: 93, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p94 = Preguntas.init(id: 94, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p95 = Preguntas.init(id: 95, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p96 = Preguntas.init(id: 96, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p97 = Preguntas.init(id: 97, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p98 = Preguntas.init(id: 98, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p99 = Preguntas.init(id: 99, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p100 = Preguntas.init(id: 100, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p101 = Preguntas.init(id: 101, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"" )
        let p102 = Preguntas.init(id: 102, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "")
        let p103 = Preguntas.init(id: 103, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p104 = Preguntas.init(id: 104, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p105 = Preguntas.init(id: 105, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p106 = Preguntas.init(id: 106, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p107 = Preguntas.init(id: 107, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p108 = Preguntas.init(id: 108, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p109 = Preguntas.init(id: 109, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p110 = Preguntas.init(id: 110, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p111 = Preguntas.init(id: 111, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p112 = Preguntas.init(id: 112, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p113 = Preguntas.init(id: 113, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p114 = Preguntas.init(id: 114, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"" )
        let p115 = Preguntas.init(id: 115, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "")
        let p116 = Preguntas.init(id: 116, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p117 = Preguntas.init(id: 117, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p118 = Preguntas.init(id: 118, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p119 = Preguntas.init(id: 119, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p120 = Preguntas.init(id: 120, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "")
        let p121 = Preguntas.init(id: 121, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p122 = Preguntas.init(id: 122, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"" )
        let p123 = Preguntas.init(id: 123, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "")
        let p124 = Preguntas.init(id: 124, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p125 = Preguntas.init(id: 125, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p126 = Preguntas.init(id: 126, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        let p127 = Preguntas.init(id: 127, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "" )
        
        
        
        // pregutnas verdad Amigables
        let amigable1 = Preguntas.init(id: 1, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "1.-¿De que carecteristica tuya eres demasiado consciente?")
        let amigable2 = Preguntas.init(id: 2, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "2.-¿Cuando fue la primera vez que fumaste?")
        let amigable3 = Preguntas.init(id: 3, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "3.-¿Has fallado en seducir a alguien? Si es así cuantas veces?")
        let amigable4 = Preguntas.init(id: 4, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "4.-¿Romperías la relación de una pareja si eso te llevase a salir con la persona de tus sueños?")
        let amigable5 = Preguntas.init(id: 5, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "5.-¿Qué tipo de borracho eres: feliz,social,difundes el amor,malvado, sexual,calmado,astuto" )
        let amigable6 = Preguntas.init(id: 6, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "6.-¿Cuanto dinero ganas?")
        let amigable7 = Preguntas.init(id: 7, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "7.-Alguna vez has engañado a tu novi@?")
        let amigable8 = Preguntas.init(id: 8, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "8.-¿Cuantas veces durante el dia piensas en el sexo?")
        let amigable9 = Preguntas.init(id: 9, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "9.-Si fueras un alimento ¿Qué serías y cómo otras personas te comerían?")
        let amigable10 = Preguntas.init(id: 10, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "10.-Si no eres gay, que persona presente sería más probable que te volviera gay" )
        let amigable11 = Preguntas.init(id: 11, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"11.-¿Cuál es el sueño mas sucio que has tenido? Describe con detalle" )
        let amigable12 = Preguntas.init(id: 12, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"12.-¿Si tuvieras que matar a alguien ¿Quién sería?")
        let amigable13 = Preguntas.init(id: 13, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable14 = Preguntas.init(id: 14, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable15 = Preguntas.init(id: 15, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable16 = Preguntas.init(id: 16, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable17 = Preguntas.init(id: 17, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable18 = Preguntas.init(id: 18, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable19 = Preguntas.init(id: 19, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable20 = Preguntas.init(id: 20, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable21 = Preguntas.init(id: 21, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable22 = Preguntas.init(id: 22, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable23 = Preguntas.init(id: 23, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"" )
        let amigable24 = Preguntas.init(id: 24, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"")
        let amigable25 = Preguntas.init(id: 25, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable26 = Preguntas.init(id: 26, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable27 = Preguntas.init(id: 27, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable28 = Preguntas.init(id: 28, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable29 = Preguntas.init(id: 29, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable30 = Preguntas.init(id: 30, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable31 = Preguntas.init(id: 31, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable32 = Preguntas.init(id: 32, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable33 = Preguntas.init(id: 33, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable34 = Preguntas.init(id: 34, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable35 = Preguntas.init(id: 35, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"" )
        let amigable36 = Preguntas.init(id: 36, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"")
        let amigable37 = Preguntas.init(id: 37, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable38 = Preguntas.init(id: 38, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable39 = Preguntas.init(id: 39, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable40 = Preguntas.init(id: 40, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable41 = Preguntas.init(id: 41, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable42 = Preguntas.init(id: 42, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable43 = Preguntas.init(id: 43, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable44 = Preguntas.init(id: 44, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable45 = Preguntas.init(id: 45, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable46 = Preguntas.init(id: 46, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable47 = Preguntas.init(id: 47, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"" )
        let amigable48 = Preguntas.init(id: 48, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"")
        let amigable49 = Preguntas.init(id: 49, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable50 = Preguntas.init(id: 50, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable51 = Preguntas.init(id: 51, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable52 = Preguntas.init(id: 52, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable53 = Preguntas.init(id: 53, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable54 = Preguntas.init(id: 54, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable55 = Preguntas.init(id: 55, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable56 = Preguntas.init(id: 56, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable57 = Preguntas.init(id: 57, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable58 = Preguntas.init(id: 58, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable59 = Preguntas.init(id: 59, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"" )
        let amigable60 = Preguntas.init(id: 60, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"")
        let amigable61 = Preguntas.init(id: 61, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable62 = Preguntas.init(id: 62, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"" )
        let amigable63 = Preguntas.init(id: 63, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"")
        let amigable64 = Preguntas.init(id: 64, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable65 = Preguntas.init(id: 65, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable66 = Preguntas.init(id: 66, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable67 = Preguntas.init(id: 67, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable68 = Preguntas.init(id: 68, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable69 = Preguntas.init(id: 69, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable70 = Preguntas.init(id: 70, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable71 = Preguntas.init(id: 71, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "")
        let amigable72 = Preguntas.init(id: 72, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "")
        let amigable73 = Preguntas.init(id: 72, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "" )
        let amigable74 = Preguntas.init(id: 73, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"" )
        let amigable75 = Preguntas.init(id: 74, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"")
        let amigable76 = Preguntas.init(id: 75, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"" )
        let amigable77 = Preguntas.init(id: 76, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"")
        
        // preguntas sexuales
        let s1 = Preguntas.init(id: 1, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "1.-Alguna vez has tenido una relación de una noche? Si es así ¿Cuántas has tenido?")
        let s2 = Preguntas.init(id: 2, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "2.-¿Alguna vez has llorado durante un orgasmo?")
        let s3 = Preguntas.init(id: 3, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "3.-¿Alguna vez has interrumpido mientras tus padres estaban teniendo sexo?")
        let s4 = Preguntas.init(id: 4, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "4.-¿Cual es tu posición sexual favorita?")
        let s5 = Preguntas.init(id: 5, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "5.-¿Alguna vez has sido suci@ en un coche?")
        let s6 = Preguntas.init(id: 6, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "6.-Recuerdas la primera vez que viste a un miembro del sexo opuesto(que no sean tus padres)desnudo?¿Qué te parecio?")
        let s7 = Preguntas.init(id: 7, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "7.-Te afeitas el vello púbico")
        let s8 = Preguntas.init(id: 8, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "8.-¿Cuantas veces durante el dia piensas en el sexo?")
        let s9 = Preguntas.init(id: 9, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s10 = Preguntas.init(id: 10, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s11 = Preguntas.init(id: 11, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s12 = Preguntas.init(id: 12, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s13 = Preguntas.init(id: 13, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s14 = Preguntas.init(id: 14, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s15 = Preguntas.init(id: 15, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s16 = Preguntas.init(id: 16, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s17 = Preguntas.init(id: 17, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s18 = Preguntas.init(id: 18, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s19 = Preguntas.init(id: 19, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s20 = Preguntas.init(id: 20, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s21 = Preguntas.init(id: 21, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s22 = Preguntas.init(id: 22, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s23 = Preguntas.init(id: 23, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s24 = Preguntas.init(id: 24, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s25 = Preguntas.init(id: 25, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s26 = Preguntas.init(id: 26, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s27 = Preguntas.init(id: 27, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s28 = Preguntas.init(id: 28, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s29 = Preguntas.init(id: 29, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s30 = Preguntas.init(id: 30, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s31 = Preguntas.init(id: 31, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s32 = Preguntas.init(id: 32, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s33 = Preguntas.init(id: 33, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s34 = Preguntas.init(id: 34, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s35 = Preguntas.init(id: 35, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s36 = Preguntas.init(id: 36, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s37 = Preguntas.init(id: 37, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s38 = Preguntas.init(id: 38, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s39 = Preguntas.init(id: 39, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        let s40 = Preguntas.init(id: 40, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        
        // Preguntas prohibidas
        let ph1 = Preguntas.init(id: 1, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph1")
        let ph2 = Preguntas.init(id: 2, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph2")
        let ph3 = Preguntas.init(id: 3, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph3")
        let ph4 = Preguntas.init(id: 4, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph4")
        let ph5 = Preguntas.init(id: 5, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph5")
        let ph6 = Preguntas.init(id: 6, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph6")
        let ph7 = Preguntas.init(id: 7, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph7")
        let ph8 = Preguntas.init(id: 8, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph8")
        
        
        //
        self.preguntas.append(p1)
        self.preguntas.append(p2)
        self.preguntas.append(p3)
        self.preguntas.append(p4)
        self.preguntas.append(p5)
        self.preguntas.append(p6)
        self.preguntas.append(p7)
        self.preguntas.append(p8)
        self.preguntas.append(p9)
        self.preguntas.append(p10)
        self.preguntas.append(p11)
        self.preguntas.append(p12)
        self.preguntas.append(p13)
        self.preguntas.append(p14)
        self.preguntas.append(p15)
        self.preguntas.append(p16)
        self.preguntas.append(p17)
        self.preguntas.append(p18)
        self.preguntas.append(p19)
        self.preguntas.append(p20)
        self.preguntas.append(p21)
        self.preguntas.append(p22)
        self.preguntas.append(p23)
        self.preguntas.append(p24)
        self.preguntas.append(p25)
        self.preguntas.append(p26)
        self.preguntas.append(p27)
        self.preguntas.append(p28)
        self.preguntas.append(p29)
        self.preguntas.append(p30)
        self.preguntas.append(p31)
        self.preguntas.append(p32)
        self.preguntas.append(p33)
        self.preguntas.append(p34)
        self.preguntas.append(p35)
        self.preguntas.append(p36)
        self.preguntas.append(p37)
        self.preguntas.append(p38)
        self.preguntas.append(p39)
        self.preguntas.append(p40)
        self.preguntas.append(p41)
        self.preguntas.append(p42)
        self.preguntas.append(p43)
        self.preguntas.append(p44)
        self.preguntas.append(p45)
        self.preguntas.append(p46)
        self.preguntas.append(p47)
        self.preguntas.append(p48)
        self.preguntas.append(p49)
        self.preguntas.append(p50)
        self.preguntas.append(p51)
        self.preguntas.append(p52)
        self.preguntas.append(p53)
        self.preguntas.append(p54)
        self.preguntas.append(p55)
        self.preguntas.append(p56)
        self.preguntas.append(p57)
        self.preguntas.append(p58)
        self.preguntas.append(p59)
        self.preguntas.append(p60)
        self.preguntas.append(p61)
        self.preguntas.append(p62)
        self.preguntas.append(p63)
        self.preguntas.append(p63)
        self.preguntas.append(p64)
        self.preguntas.append(p65)
        self.preguntas.append(p66)
        self.preguntas.append(p67)
        self.preguntas.append(p68)
        self.preguntas.append(p69)
        self.preguntas.append(p70)
        self.preguntas.append(p71)
        self.preguntas.append(p72)
        self.preguntas.append(p73)
        self.preguntas.append(p74)
        self.preguntas.append(p75)
        self.preguntas.append(p76)
        self.preguntas.append(p77)
        self.preguntas.append(p78)
        self.preguntas.append(p79)
        self.preguntas.append(p80)
        self.preguntas.append(p81)
        self.preguntas.append(p82)
        self.preguntas.append(p83)
        self.preguntas.append(p84)
        self.preguntas.append(p85)
        self.preguntas.append(p86)
        self.preguntas.append(p87)
        self.preguntas.append(p88)
        self.preguntas.append(p89)
        self.preguntas.append(p90)
        self.preguntas.append(p91)
        self.preguntas.append(p92)
        self.preguntas.append(p93)
        self.preguntas.append(p94)
        self.preguntas.append(p95)
        self.preguntas.append(p96)
        self.preguntas.append(p97)
        self.preguntas.append(p98)
        self.preguntas.append(p99)
        self.preguntas.append(p100)
        self.preguntas.append(p101)
        self.preguntas.append(p102)
        self.preguntas.append(p103)
        self.preguntas.append(p104)
        self.preguntas.append(p105)
        self.preguntas.append(p106)
        self.preguntas.append(p107)
        self.preguntas.append(p108)
        self.preguntas.append(p109)
        self.preguntas.append(p110)
        self.preguntas.append(p111)
        self.preguntas.append(p112)
        self.preguntas.append(p113)
        self.preguntas.append(p114)
        self.preguntas.append(p115)
        self.preguntas.append(p116)
        self.preguntas.append(p117)
        self.preguntas.append(p118)
        self.preguntas.append(p119)
        self.preguntas.append(p120)
        self.preguntas.append(p121)
        self.preguntas.append(p122)
        self.preguntas.append(p123)
        self.preguntas.append(p124)
        self.preguntas.append(p125)
        self.preguntas.append(p126)
        self.preguntas.append(p127)
        
        //
        self.preguntas.append(amigable1)
        self.preguntas.append(amigable2)
        self.preguntas.append(amigable3)
        self.preguntas.append(amigable4)
        self.preguntas.append(amigable5)
        self.preguntas.append(amigable6)
        self.preguntas.append(amigable7)
        self.preguntas.append(amigable8)
        self.preguntas.append(amigable9)
        self.preguntas.append(amigable10)
        self.preguntas.append(amigable11)
        self.preguntas.append(amigable12)
        self.preguntas.append(amigable13)
        self.preguntas.append(amigable14)
        self.preguntas.append(amigable15)
        self.preguntas.append(amigable16)
        self.preguntas.append(amigable17)
        self.preguntas.append(amigable18)
        self.preguntas.append(amigable19)
        self.preguntas.append(amigable20)
        self.preguntas.append(amigable21)
        self.preguntas.append(amigable22)
        self.preguntas.append(amigable23)
        self.preguntas.append(amigable24)
        self.preguntas.append(amigable25)
        self.preguntas.append(amigable26)
        self.preguntas.append(amigable27)
        self.preguntas.append(amigable28)
        self.preguntas.append(amigable29)
        self.preguntas.append(amigable30)
        self.preguntas.append(amigable31)
        self.preguntas.append(amigable32)
        self.preguntas.append(amigable33)
        self.preguntas.append(amigable34)
        self.preguntas.append(amigable35)
        self.preguntas.append(amigable36)
        self.preguntas.append(amigable37)
        self.preguntas.append(amigable38)
        self.preguntas.append(amigable39)
        self.preguntas.append(amigable40)
        self.preguntas.append(amigable41)
        self.preguntas.append(amigable42)
        self.preguntas.append(amigable43)
        self.preguntas.append(amigable44)
        self.preguntas.append(amigable45)
        self.preguntas.append(amigable46)
        self.preguntas.append(amigable47)
        self.preguntas.append(amigable48)
        self.preguntas.append(amigable49)
        self.preguntas.append(amigable50)
        self.preguntas.append(amigable51)
        self.preguntas.append(amigable52)
        self.preguntas.append(amigable53)
        self.preguntas.append(amigable54)
        self.preguntas.append(amigable55)
        self.preguntas.append(amigable56)
        self.preguntas.append(amigable57)
        self.preguntas.append(amigable58)
        self.preguntas.append(amigable59)
        self.preguntas.append(amigable60)
        self.preguntas.append(amigable61)
        self.preguntas.append(amigable62)
        self.preguntas.append(amigable63)
        self.preguntas.append(amigable64)
        self.preguntas.append(amigable65)
        self.preguntas.append(amigable66)
        self.preguntas.append(amigable67)
        self.preguntas.append(amigable68)
        self.preguntas.append(amigable69)
        self.preguntas.append(amigable70)
        self.preguntas.append(amigable71)
        self.preguntas.append(amigable72)
        self.preguntas.append(amigable73)
        self.preguntas.append(amigable74)
        self.preguntas.append(amigable75)
        self.preguntas.append(amigable76)
        self.preguntas.append(amigable77)
        //
        self.preguntas.append(s1)
        self.preguntas.append(s2)
        self.preguntas.append(s3)
        self.preguntas.append(s4)
        self.preguntas.append(s5)
        self.preguntas.append(s6)
        self.preguntas.append(s7)
        self.preguntas.append(s8)
        self.preguntas.append(s9)
        self.preguntas.append(s10)
        self.preguntas.append(s11)
        self.preguntas.append(s12)
        self.preguntas.append(s13)
        self.preguntas.append(s14)
        self.preguntas.append(s15)
        self.preguntas.append(s16)
        self.preguntas.append(s17)
        self.preguntas.append(s18)
        self.preguntas.append(s19)
        self.preguntas.append(s20)
        self.preguntas.append(s21)
        self.preguntas.append(s22)
        self.preguntas.append(s23)
        self.preguntas.append(s24)
        self.preguntas.append(s25)
        self.preguntas.append(s26)
        self.preguntas.append(s27)
        self.preguntas.append(s28)
        self.preguntas.append(s29)
        self.preguntas.append(s30)
        self.preguntas.append(s31)
        self.preguntas.append(s32)
        self.preguntas.append(s33)
        self.preguntas.append(s34)
        self.preguntas.append(s35)
        self.preguntas.append(s36)
        self.preguntas.append(s37)
        self.preguntas.append(s38)
        self.preguntas.append(s39)
        self.preguntas.append(s40)
        //
        self.preguntas.append(ph1)
        self.preguntas.append(ph2)
        self.preguntas.append(ph3)
        self.preguntas.append(ph4)
        self.preguntas.append(ph5)
        self.preguntas.append(ph6)
        self.preguntas.append(ph7)
        self.preguntas.append(ph8)
        
        
        
        
        
    }
    
    func changeStatusVerdad(status : Bool) -> Void {
        for pregunta in preguntas{
            if (pregunta.subcategoria == .Inocentes){
                pregunta.status = status
            }
            
        }
        
    }
    func changeStatusAmigables(status : Bool) -> Void {
        for pregunta in preguntas{
            if (pregunta.subcategoria == .Amigables){
                pregunta.status = status
            }
            
        }
        
    }
    
    func changeStatusSexuales(status : Bool) -> Void {
        for pregunta in preguntas{
            if (pregunta.subcategoria == .Sexuales){
                pregunta.status = status
            }
            
        }
        
    }
    
    func changeStatusProhibidas(status : Bool) -> Void {
        for pregunta in preguntas{
            if (pregunta.subcategoria == .Prohibidas){
                pregunta.status = status
            }
            
        }
        
    }
    
}
