//
//  StringVerdadReto.swift
//  True Dare or shots
//
//  Created by Diego on 20/09/18.
//  Copyright © 2018 diego. All rights reserved.
//

import Foundation





//Inocentes
let arrayverdad1 = [
    "1.-Si fueras un alimento ¿Qué serías y ¿cómo otras personas te comerían?",
    "2.-¿Con qué tipo de persona te gustaría casarte algún dia?",
    "3.-¿Cuál es tu talento secreto?",
    "4.-¿Si tuvieras la oportunidad de volver a nacer como alguien más en este cuarto,¿quién sería?¿Por qué?",
    "5.-Si le va a dar consejo de (no hagas lo que yo hice) a una persona mas joven ¿qué sería?",
    "6.-¿Cuál es tu idea de una cita perfecta?",
    "7.-¿Alguna vez has besado al hermano o hermana de un amigo?",
    "8.-¿Cuándo has amado a alguien que no te haya amado de vuelta?",
    "9.-¿Cuando tuviste tu primer beso y cómo fue?",
    "10.-¿De que tienes miedo?",
    "11.-¿Cuál es tu mayor secreto?",
    "12.-Si pudieras cambiar una cosa en tu cuerpo, ¿cuál sería?",
    "13.- Si tuvieras la oportunidad de salir en una cita con alguien que está presente, ¿quién sería?",
    "14.-Si pudieras tener una relación con un/a famoso/a, ¿quién sería",
    "15.-¿Cuál ha sido el peor día de tu vida?",
    "16.-¿Qué es lo más loco que has hecho por un chico o una chica?",
    "17.-¿Te arrepientes de algo en esta vida?",
    "18.- ¿Qué es lo más estúpido que has hecho nunca?",
    "19.-¿Qué es lo que la mayoría de gente piensa de ti y es totalmente falso?",
    "20.-¿Cuál es la cosa más infantil que todavía haces?",
    "21.-¿Dejarías a tu pareja si te ofrecieran 1 millón de euros?",
    "22.-¿Cómo fue tu primer beso?",
    "23.-",
    "24.-",
    "25.-",
    "26.-",
    "27.-",
    "28.-",
    "29.-",
    "30.-",
    "31.-",
    "32.-",
    "33.-",
    "34.-",
    "35.-",
    "36.-",
    "37.-",
    "38.-",
    "39.-",
    "40.-",
    "41.-",
    "42.-",
    "43.-",
    "44.-",
    "45.-",
    "46.-",
    "47.-",
    "48.-",
    "49.-",
    "50.-",
    "51.-",
    "52.-",
    "53.-",
    "54.-",
    "55.-",
    "56.-",
    "57.-",
    "58.-",
    "59.-"]


//Amigables
let arrayverdad2 = [
    "1.-¿De que carecteristica tuya eres demasiado consciente?",
     "2.-¿Cuando fue la primera vez que fumaste?",
     "3.-¿Has fallado en seducir a alguien? Si es así cuantas veces?",
     "4.-¿Romperías la relación de una pareja si eso te llevase a salir con la persona de tus sueños?",
     "5.-¿Qué tipo de borracho eres: feliz,social,difundes el amor,malvado, sexual,calmado,astuto",
     "6.-¿Cuanto dinero ganas?",
     "7.-Alguna vez has engañado a tu novi@?",
     "8.-¿Cuantas veces durante el dia piensas en el sexo?",
     "9.-Si fueras un alimento ¿Qué serías y cómo otras personas te comerían?",
     "10.-Si no eres gay, que persona presente sería más probable que te volviera gay",
     "11.-¿Cuál es el sueño mas sucio que has tenido? Describe con detalle",
     "12.-¿Si tuvieras que matar a alguien ¿Quién sería?",
     "13.-¿Cuál es tu talento secreto?",
     "14.-¿Si tuvieras la oportunidad de volver a nacer como alguien más en este cuarto,¿quién sería?¿Por qué?",
     "15.-Entre todas las personas en esta sala, con qué persona lo hárias?",
     "16.-¿Cual es la cosa más loca que has hecho desnudo?",
     "17.-Redtube, Youporn o PornHub? ¿Cuál y porque..?",
     "18.-¿Alguna vez has besado a alguien del mismo sexo? ¿Quien?",
     "19.-¿Alguna vez has acosado a alguien? Si lo has ¿Quién fue?",
     "20.-¿Cuando tuviste tu primer beso y cómo fue?",
     "21.- Si tuvieras la oportunidad de salir en una cita con alguien que está presente, ¿quién sería?",
     "22.-Si pudieras tener sexo con un/a famoso/a, ¿quién sería",
     "23.-",
     "24.-",
     "25.-",
     "26.-",
     "27.-",
     "28.-",
     "29.-",
     "30.-",
     "31.-",
     "32.-",
     "33.-",
     "34.-",
     "35.-",
     "36.-",
     "37.-",
     "38.-",
     "39.-",
     "40.-",
     "41.-",
     "42.-",
     "43.-",
     "44.-",
     "45.-",
     "46.-",
     "47.-",
     "48.-",
     "49.-",
     "50.-",
     "51.-",
     "52.-",
     "53.-",
     "54.-",
     "55.-",
     "56.-",
     "57.-",
     "58.-",
     "59.-"]

//Sexuales
let arrayverdad3 = [
    "1.-Alguna vez has tenido una relación de una noche? Si es así ¿Cuántas has tenido?",
    "2.-¿Alguna vez has llorado durante un orgasmo?",
    "3.-¿Alguna vez has interrumpido mientras tus padres estaban teniendo sexo?",
    "4.-¿Cual es tu posición sexual favorita?",
    "5.-¿Alguna vez has sido suci@ en un coche?",
    "6.-Recuerdas la primera vez que viste a un miembro del sexo opuesto(que no sean tus padres)desnudo?¿Qué te parecio?",
    "7.-Te afeitas el vello púbico",
    "8.-¿Cuantas veces durante el dia piensas en el sexo?",
    "9.-¿Alguna vez has llegado al orgasmo con toda la ropa puesta?",
    "10.-¿Cuando te comenzaste a masturbar?",
    "11.-¿Recibes o das más?",
    "12.-Entre todas las personas en esta sala, con qué persona lo hárias?",
    "13.-¿Alguna vez has intimado a alguien?",
    "14.-El jugador a tu derecha debe contestar si ha tenido relaciones sexuales con alguien que conozcas, si es asi ¿quién era, cómo era? y darles una calificación.",
    "15.-¿Cuál es tu mayor provocación sexual?",
    "16.-¿Cuál es tu más profunda, más oscura fantasía?",
    "17.-¿Alguna vez has usado lubricante?",
    "18.-¿Con quién en el gruoo tendrías sexo y ¿ por qué tendrias sexo con él o ella?",
    "19.-Redtube, Youporn o PornHub? ¿Cuál y porque..?",
    "20.-¿Has tomado la virginidad de multiples personas?",
    "21.-¿Cuál es el menor tiempo que has tardado en llegar a un orgasmo?",
    "22.-¿Cómo te sentirías si pillas a tu pareja dándose autoplacer?",
    "23.-¿Cuál es tu fantasía sexual más deseada?",
    "24.-¿Con cuántas personas te has acostado?",
    "25.-",
    "26.-",
    "27.-",
    "28.-",
    "29.-",
    "30.-",
    "31.-",
    "32.-",
    "33.-",
    "34.-",
    "35.-",
    "36.-",
    "37.-",
    "38.-",
    "39.-",
    "40.-",
    "41.-",
    "42.-",
    "43.-",
    "44.-",
    "45.-",
    "46.-",
    "47.-",
    "48.-",
    "49.-",
    "50.-",
    "51.-",
    "52.-",
    "53.-",
    "54.-",
    "55.-",
    "56.-",
    "57.-",
    "58.-",
    "59.-"]



//Prohibidas
let arrayverdad4 = [
    "1.-",
    "2.-",
    "3.-",
    "4.-",
    "5.-",
    "6.-",
    "7.-",
    "8.-",
    "9.-",
    "10.-",
    "11.-",
    "12.-",
    "13.-",
    "14.-",
    "15.-",
    "16.-",
    "17.-",
    "18.-",
    "19.-",
    "20.-",
    "21.-",
    "22.-",
    "23.-",
    "24.-",
    "25.-",
    "26.-",
    "27.-",
    "28.-",
    "29.-",
    "30.-",
    "31.-",
    "32.-",
    "33.-",
    "34.-",
    "35.-",
    "36.-",
    "37.-",
    "38.-",
    "39.-",
    "40.-",
    "41.-",
    "42.-",
    "43.-",
    "44.-",
    "45.-",
    "46.-",
    "47.-",
    "48.-",
    "49.-",
    "50.-",
    "51.-",
    "52.-",
    "53.-",
    "54.-",
    "55.-",
    "56.-",
    "57.-",
    "58.-",
    "59.-"]


