//
//  Categorias.swift
//  True Dare or shots
//
//  Created by Joel Lozano on 02/10/18.
//  Copyright © 2018 diego. All rights reserved.
//

import Foundation

class CategoriasVerdad{
    
    
    enum categories {
        case Verdad
        case Reto
        case Shot
    }
    
    enum subcategori{
        case Inocentes
        case Amigables
        case Sexuales
        case Prohibidas
    }
    var categoria :categories
    var subCategoria: subcategori
    var preguntas = [Preguntas]()
    
    init() {
        categoria = .Verdad
        subCategoria = .Inocentes
        // preguntas verdad inocentes
        let p1 = Preguntas.init(id: 1, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nSi fueras un alimento ¿Qué serías y ¿cómo otras personas te comerían?")
        let p2 = Preguntas.init(id: 2, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Con qué tipo de persona te gustaría casarte algún dia?")
        let p3 = Preguntas.init(id: 3, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es tu talento secreto?")
        let p4 = Preguntas.init(id: 4, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Si tuvieras la oportunidad de volver a nacer como alguien más en este cuarto,¿quién sería?¿Por qué?" )
        let p5 = Preguntas.init(id: 5, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nSi le va a dar consejo de (no hagas lo que yo hice) a una persona mas joven ¿qué sería?" )
        let p6 = Preguntas.init(id: 6, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es tu idea de una cita perfecta?" )
        let p7 = Preguntas.init(id: 7, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez has besado al hermano o hermana de un amigo?" )
        let p8 = Preguntas.init(id: 8, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuándo has amado a alguien que no te haya amado de vuelta?")
        let p9 = Preguntas.init(id: 9, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuando tuviste tu primer beso y cómo fue?" )
        let p10 = Preguntas.init(id: 10, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿De que tienes miedo?" )
        let p11 = Preguntas.init(id: 11, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\n¿Cuál es tu mayor secreto?")
        let p12 = Preguntas.init(id: 12, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nSi pudieras cambiar una cosa en tu cuerpo, ¿cuál sería?" )
        let p13 = Preguntas.init(id: 13, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nSi tuvieras la oportunidad de salir en una cita con alguien que está presente, ¿quién sería?" )
        let p14 = Preguntas.init(id: 14, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nSi pudieras tener una relación con un/a famoso/a, ¿quién sería?")
        let p15 = Preguntas.init(id: 15, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál ha sido el peor día de tu vida?")
        let p16 = Preguntas.init(id: 16, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué es lo más loco que has hecho por un chico o una chica?")
        let p17 = Preguntas.init(id: 17, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Te arrepientes de algo en esta vida?" )
        let p18 = Preguntas.init(id: 18, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué es lo más estúpido que has hecho nunca?" )
        let p19 = Preguntas.init(id: 19, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué es lo que la mayoría de gente piensa de ti y es totalmente falso?" )
        let p20 = Preguntas.init(id: 20, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es la cosa más infantil que todavía haces?" )
        let p21 = Preguntas.init(id: 21, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Dejarías a tu pareja si te ofrecieran 1 millón de euros?")
        let p22 = Preguntas.init(id: 22, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cómo fue tu primer beso?" )
        let p23 = Preguntas.init(id: 23, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿Te gusta tu trabajo/escuela? ¿Por qué?" )
        let p24 = Preguntas.init(id: 24, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\n¿Qué es lo más loco que has hecho en la vida?")
        let p25 = Preguntas.init(id: 25, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Has mentido a alguien para no herir sus sentimientos?" )
        let p26 = Preguntas.init(id: 26, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué cualidad física te hace caer rendido/a a los pies de alguien?" )
        let p27 = Preguntas.init(id: 27, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es el sitio más extraño en que has conocido a una persona con la que terminaste saliendo?")
        let p28 = Preguntas.init(id: 28, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué es lo más extraño que has buscado en internet?")
        let p29 = Preguntas.init(id: 29, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es la cosa más infantil que todavía haces?")
        let p30 = Preguntas.init(id: 30, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué no has contado nunca a nadie?" )
        let p31 = Preguntas.init(id: 31, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuándo ha sido el momento más inapropiado de tu vida en que te has tirado un pedo?" )
        let p32 = Preguntas.init(id: 32, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nSi tuvieras un control remoto que funciona sobre cualquier cosa, ¿qué controlaría?" )
        let p33 = Preguntas.init(id: 33, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es el hábito más repugnante que tienes?" )
        let p34 = Preguntas.init(id: 34, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué quieres que tus padres nunca sepan?")
        let p35 = Preguntas.init(id: 35, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿A quién salvarías si viene un meteorito y solo puedes salvar a una persona?" )
        let p36 = Preguntas.init(id: 36, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿Cuál es tu estrategia para conquistar a una mujer/hombre?" )
        let p37 = Preguntas.init(id: 37, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\n¿Qué es lo más loco que has hecho sin que tus padres lo sepan?")
        let p38 = Preguntas.init(id: 38, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué harías si tus padres te dejaran en casa durante una semana entera?" )
        let p39 = Preguntas.init(id: 39, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez te gustó uno de tus profesores en la escuela?" )
        let p40 = Preguntas.init(id: 40, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es la foto más vergonzosa de ti?")
        let p41 = Preguntas.init(id: 41, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué cosa mala has hecho que nadie descubrió?")
        let p42 = Preguntas.init(id: 42, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es la cosa más tonta a la que tienes un apego emocional?")
        let p43 = Preguntas.init(id: 43, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es tu miedo más oscuro?" )
        let p44 = Preguntas.init(id: 44, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez has mentido acerca de estar enfermo para que puedas quedarte en casa y no ir al trabajo o a la escuela?" )
        let p45 = Preguntas.init(id: 45, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es el lugar más extraño en el que has orinado?" )
        let p46 = Preguntas.init(id: 46, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez te has hecho caca en los pantalones desde que eras un niño?" )
        let p47 = Preguntas.init(id: 47, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuándo fue la última vez que te orinaste en la cama?")
        let p48 = Preguntas.init(id: 48, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nSi pudieras volver a hacer una cosa que hiciste cuando eras un niño, ¿cuál sería?" )
        let p49 = Preguntas.init(id: 49, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿Cuál es la cosa más grosera que ha salido de tu cuerpo?" )
        let p50 = Preguntas.init(id: 50, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\n¿Alguna vez te has tirado un pedo fuerte en clase?")
        let p51 = Preguntas.init(id: 51, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Con qué frecuencia lavas tu ropa interior?" )
        let p52 = Preguntas.init(id: 52, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez has probado la cera del oído?" )
        let p53 = Preguntas.init(id: 53, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nAlguna vez le enviaste un texto inapropiado a tu mamá o papá por accidente?")
        let p54 = Preguntas.init(id: 54, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Has llegado a olfatear tu ropa interior para saber si está limpia?")
        let p55 = Preguntas.init(id: 55, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué es lo más desagradable que has hecho en lugar público?")
        let p56 = Preguntas.init(id: 56, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué harías si supieras que el mundo acabará mañana?" )
        let p57 = Preguntas.init(id: 57, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué has hecho alguna vez y no has contado a nadie?" )
        let p58 = Preguntas.init(id: 58, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuándo fue la última vez que cantaste y bailaste solo?" )
        let p59 = Preguntas.init(id: 59, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Quién tiene los ojos más hermosos de todas las personas presentes?" )
        let p60 = Preguntas.init(id: 60, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿A qué persona famosa besarías?")
        let p61 = Preguntas.init(id: 61, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿ A quién llevarías contigo si te quedarás naufrago durante 3 días en una isla?" )
        let p62 = Preguntas.init(id: 62, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿Qué harías si fueras invisible por un día?" )
        let p63 = Preguntas.init(id: 63, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\n¿Cuánto es el tiempo máximo que has pasado sin darte un baño?")
        let p64 = Preguntas.init(id: 64, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Quién es la persona que más sabe de ti y qué tipo de secretos sobre tu vida guarda?" )
        let p65 = Preguntas.init(id: 65, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿De qué color es tu ropa interior?" )
        let p66 = Preguntas.init(id: 66, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es el lugar más extraño en el que has tenido que ir al baño?")
        let p67 = Preguntas.init(id: 67, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cómo sería tu primera cita perfecta?")
        let p68 = Preguntas.init(id: 68, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál crees que es la parte más atractiva de tu cuerpo?")
        let p69 = Preguntas.init(id: 69, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué es lo primero que le miras a una mujer o un hombre cuando lo conoces?" )
        let p70 = Preguntas.init(id: 70, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez hiciste trampa en la escuela para pasar un examen?" )
        let p71 = Preguntas.init(id: 71, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué estarías dispuesto a hacer por un millón de dólares?" )
        let p72 = Preguntas.init(id: 72, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Te has enamorado de alguien alguna vez y no se lo has contado?" )
        let p73 = Preguntas.init(id: 73, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es tu fantasía más deseada?")
        let p74 = Preguntas.init(id: 74, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál fue el momento más embarazoso de tu vida?" )
        let p75 = Preguntas.init(id: 75, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿Cuál es la cosa más embarazosa que tus padres te han pillado haciendo?" )
        let p76 = Preguntas.init(id: 76, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\nCuál es la comida más exótica que has comido")
        let p77 = Preguntas.init(id: 77, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué te gustaría cambiar de tu cuerpo?" )
        let p78 = Preguntas.init(id: 78, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Quién es tu persona favorita y por qué?" )
        let p79 = Preguntas.init(id: 79, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué película elegirías si pudieras convertirla en tu vida?")
        let p80 = Preguntas.init(id: 80, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es tu película favorita de Disney y por qué?")
        let p81 = Preguntas.init(id: 81, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué harías con un millón de dólares si alguna vez ganaras la lotería?")
        let p82 = Preguntas.init(id: 82, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nDanos una lista de 10 artículos o cosas que compraste y nunca utilizaste o lamentaste comprar" )
        let p83 = Preguntas.init(id: 83, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál ha sido tu mayor humillación?" )
        let p84 = Preguntas.init(id: 84, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué es lo más loco que te ha pasado en un centro comercial?" )
        let p85 = Preguntas.init(id: 85, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es la broma más cruel que le has gastado a alguien?" )
        let p86 = Preguntas.init(id: 86, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es la peor mentira que le has dicho a tus padres?")
        let p87 = Preguntas.init(id: 87, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es la cosa que más te molesta que hace tu mamá?" )
        let p88 = Preguntas.init(id: 88, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿Cuál es la cosa que más te molesta de tu papa?" )
        let p89 = Preguntas.init(id: 89, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\n¿Cuál es la historia más divertida que tus abuelos te han contado?")
        let p90 = Preguntas.init(id: 90, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál era tu canción favorita en tu infancia?" )
        let p91 = Preguntas.init(id: 91, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cómo es la casa de tus sueños?" )
        let p92 = Preguntas.init(id: 92, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Has llevado la misma ropa por más de 3 días?")
        let p93 = Preguntas.init(id: 93, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué animal serías?")
        let p94 = Preguntas.init(id: 94, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué dinosaurio serías?")
        let p95 = Preguntas.init(id: 95, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué supervillano serías?" )
        let p96 = Preguntas.init(id: 96, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Con qué celebridad estás obsesionado?" )
        let p97 = Preguntas.init(id: 97, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es el video YouTube más divertido que has visto?" )
        let p98 = Preguntas.init(id: 98, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Quién es el peor maestro que has tenido y por qué?" )
        let p99 = Preguntas.init(id: 99, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es tu equipo deportivo favorito?")
        let p100 = Preguntas.init(id: 100, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál es tu canción favorita en este momento?" )
        let p101 = Preguntas.init(id: 101, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿Podrías pasar dos meses sin hablar con tus amigos?" )
        let p102 = Preguntas.init(id: 102, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\n¿Podrías pasar dos meses sin tu teléfono?")
        let p103 = Preguntas.init(id: 103, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Podrías pasar dos meses sin ver televisión?" )
        let p104 = Preguntas.init(id: 104, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Podrías pasar dos meses sin conectarte a las redes sociales?" )
        let p105 = Preguntas.init(id: 105, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué prejuicio albergas secretamente?")
        let p106 = Preguntas.init(id: 106, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Si pudieras salir con algún famoso con quién sería?")
        let p107 = Preguntas.init(id: 107, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué es lo más gracioso que te ha sucedido durante una cita romántica?")
        let p108 = Preguntas.init(id: 108, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué harías si te encontraras mucho dinero en la calle?" )
        let p109 = Preguntas.init(id: 109, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿En qué condiciones le mentirías a un amigo?" )
        let p110 = Preguntas.init(id: 110, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál creerías que puede ser una pregunta bastante incómoda?" )
        let p111 = Preguntas.init(id: 111, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez has robado algo? ¿Qué robaste y por qué lo hiciste?" )
        let p112 = Preguntas.init(id: 112, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Si no estuvieras aquí, que estarías haciendo en este momento?")
        let p113 = Preguntas.init(id: 113, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Si pudieras hacer lo que quisieras, cuál sería tu trabajo soñado?" )
        let p114 = Preguntas.init(id: 114, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿Qué quieres hacer durante los próximos años?" )
        let p115 = Preguntas.init(id: 115, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\nSi pudieras ser otra persona, ¿quién serías?")
        let p116 = Preguntas.init(id: 116, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué te gustaría inventar?" )
        let p117 = Preguntas.init(id: 117, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\nSi pudieras nacer de nuevo, ¿dónde te gustaría nacer? ¿Quién te gustaría ser?" )
        let p118 = Preguntas.init(id: 118, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez has actuado como un loco en un lugar público?" )
        let p119 = Preguntas.init(id: 119, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez has pretendido ser quien no eres para obtener algún beneficio?" )
        let p120 = Preguntas.init(id: 120, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Qué harías si pudieras viajar en el tiempo?")
        let p121 = Preguntas.init(id: 121, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Alguna vez has espiado a alguien?" )
        let p122 = Preguntas.init(id: 122, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:"PREGUNTA INOCENTE\n\n¿Qué es lo que más te molesta?" )
        let p123 = Preguntas.init(id: 123, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta:  "PREGUNTA INOCENTE\n\n¿Qué harías si ganaras la lotería?")
        let p124 = Preguntas.init(id: 124, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál ha sido el piropo más extraño que te han dicho?" )
        let p125 = Preguntas.init(id: 125, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál ha sido el peor rumor que has compartido? (sabiendo que no era cierto)" )
        let p126 = Preguntas.init(id: 126, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál ha sido el evento más traumático de tu vida?" )
        let p127 = Preguntas.init(id: 127, status: true, categoria: .Verdad, subcategoria:.Inocentes, pregunta: "PREGUNTA INOCENTE\n\n¿Cuál ha sido la peor fiesta a la que has ido?" )
        
        
        
        // pregutnas verdad Amigables
        let amigable1 = Preguntas.init(id: 1, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\n¿De que carecteristica tuya eres demasiado consciente?")
        let amigable2 = Preguntas.init(id: 2, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuando fue la primera vez que fumaste?")
        let amigable3 = Preguntas.init(id: 3, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Has fallado en seducir a alguien? Si es así cuantas veces?")
        let amigable4 = Preguntas.init(id: 4, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Romperías la relación de una pareja si eso te llevase a salir con la persona de tus sueños?")
        let amigable5 = Preguntas.init(id: 5, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Qué tipo de borracho eres: feliz,social,difundes el amor,malvado, sexual,calmado,astuto" )
        let amigable6 = Preguntas.init(id: 6, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuanto dinero ganas?")
        let amigable7 = Preguntas.init(id: 7, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\nAlguna vez has engañado a tu novi@?")
        let amigable8 = Preguntas.init(id: 8, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuantas veces durante el dia piensas en el sexo?")
        let amigable9 = Preguntas.init(id: 9, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\nSi fueras un alimento ¿Qué serías y cómo otras personas te comerían?")
        let amigable10 = Preguntas.init(id: 10, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\nSi no eres gay, que persona presente sería más probable que te volviera gay" )
        let amigable11 = Preguntas.init(id: 11, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Cuál es el sueño mas sucio que has tenido? Describe con detalle" )
        let amigable12 = Preguntas.init(id: 12, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Si tuvieras que matar a alguien ¿Quién sería?")
        let amigable13 = Preguntas.init(id: 13, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\n¿Cuál es tu talento secreto?")
        let amigable14 = Preguntas.init(id: 14, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Si tuvieras la oportunidad de volver a nacer como alguien más en este cuarto,¿quién sería?¿Por qué?")
        let amigable15 = Preguntas.init(id: 15, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\nEntre todas las personas en esta sala, con qué persona lo hárias?")
        let amigable16 = Preguntas.init(id: 16, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cual es la cosa más loca que has hecho desnudo?")
        let amigable17 = Preguntas.init(id: 17, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\nRedtube, Youporn o PornHub? ¿Cuál y porque..?" )
        let amigable18 = Preguntas.init(id: 18, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Alguna vez has besado a alguien del mismo sexo? ¿Quien?")
        let amigable19 = Preguntas.init(id: 19, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Alguna vez has acosado a alguien? Si lo has ¿Quién fue?")
        let amigable20 = Preguntas.init(id: 20, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuando tuviste tu primer beso y cómo fue?")
        let amigable21 = Preguntas.init(id: 21, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\nSi tuvieras la oportunidad de salir en una cita con alguien que está presente, ¿quién sería?")
        let amigable22 = Preguntas.init(id: 22, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\nSi pudieras tener sexo con un/a famoso/a, ¿quién sería" )
        let amigable23 = Preguntas.init(id: 23, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Te gusta alguien ahora mismo?" )
        let amigable24 = Preguntas.init(id: 24, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Has sentido atracción por algún amigo/a de tu pareja actual o anteriores?")
        let amigable25 = Preguntas.init(id: 25, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\n¿Has confesado un secreto a alguien en confianza y éste lo ha contado? ¿Qué era?")
        let amigable26 = Preguntas.init(id: 26, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Has mentido a alguien para no herir sus sentimientos?")
        let amigable27 = Preguntas.init(id: 27, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Tus padres te han pillado dándote autoplacer?")
        let amigable28 = Preguntas.init(id: 28, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuál fue el motivo de tu última ruptura de pareja?")
        let amigable29 = Preguntas.init(id: 29, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Alguna vez has sido infiel?" )
        let amigable30 = Preguntas.init(id: 30, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\nSi ves accidentalmente una una persona del sexo opuesto desnuda y no lo sabe, ¿seguirías mirando?")
        let amigable31 = Preguntas.init(id: 31, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Has tenido conversaciones subidas de tono por chat o WhatsApp?")
        let amigable32 = Preguntas.init(id: 32, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Qué edad tenía la persona más mayor de las que has tenido relaciones?")
        let amigable33 = Preguntas.init(id: 33, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\n¿Qué edad tenía la persona más joven de las que has tenido relaciones?")
        let amigable34 = Preguntas.init(id: 34, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Sientes o has sentido atracción física por algún familiar lejano?" )
        let amigable35 = Preguntas.init(id: 35, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\nSi algún día te casas, ¿dónde te gustaría que fuera la ceremonia?" )
        let amigable36 = Preguntas.init(id: 36, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Cuál es el hábito más repugnante que tienes?")
        let amigable37 = Preguntas.init(id: 37, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\n¿Qué quieres que tus padres nunca sepan?")
        let amigable38 = Preguntas.init(id: 38, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Qué harías si tus padres te dejaran en casa durante una semana entera?")
        let amigable39 = Preguntas.init(id: 39, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuál es la cosa más cara que has robado?")
        let amigable40 = Preguntas.init(id: 40, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Quién es la persona que más has lamentado besar?")
        let amigable41 = Preguntas.init(id: 41, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Quién tiene el mejor trasero de todos los que estamos aquí?" )
        let amigable42 = Preguntas.init(id: 42, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuál de los jugadores de este grupo tiene una boca más sensual?")
        let amigable43 = Preguntas.init(id: 43, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuál es la parte del cuerpo que encuentra más atractiva en una persona del otro (o mismo) género?")
        let amigable44 = Preguntas.init(id: 44, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuál de las personas dentro de este grupo crees que ha mejorado su apariencia física?")
        let amigable45 = Preguntas.init(id: 45, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\n¿Crees que alguna de las personas que se encuentran aquí tiene una pareja que no le conviene? ¿Quién? ¿Por qué?")
        let amigable46 = Preguntas.init(id: 46, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Con quién saldrías de aquí en una cita?" )
        let amigable47 = Preguntas.init(id: 47, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Alguna vez has orinado en una piscina?" )
        let amigable48 = Preguntas.init(id: 48, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Qué es lo primero que le miras a una mujer o un hombre cuando lo conoces?")
        let amigable49 = Preguntas.init(id: 49, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\n¿Alguna vez hiciste trampa en la escuela para pasar un examen?")
        let amigable50 = Preguntas.init(id: 50, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cómo fue tu primer beso?")
        let amigable51 = Preguntas.init(id: 51, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Qué estarías dispuesto a hacer por un millón de dólares?")
        let amigable52 = Preguntas.init(id: 52, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuál fue el encuentro romántico más incómodo que tuviste?")
        let amigable53 = Preguntas.init(id: 53, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Has hecho cosas borracho que al día siguiente no recuerdes?" )
        let amigable54 = Preguntas.init(id: 54, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Qué es lo más loco que has hecho mientras estabas borracho?")
        let amigable55 = Preguntas.init(id: 55, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Quién es la persona más sexy aquí?")
        let amigable56 = Preguntas.init(id: 56, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\nEn qué país te gustaría vivir si tuvieras la oportunidad")
        let amigable57 = Preguntas.init(id: 57, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\n¿Alguna vez has contado una mentira durante un juego de verdad o reto? ¿Qué fue y por qué?")
        let amigable58 = Preguntas.init(id: 58, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuál es la broma más cruel que le has gastado a alguien?" )
        let amigable59 = Preguntas.init(id: 59, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Cuál es la cosa más embarazosa que has puesto en las redes sociales?" )
        let amigable60 = Preguntas.init(id: 60, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Cuál es la peor mentira que le has dicho a tus padres?")
        let amigable61 = Preguntas.init(id: 61, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿En qué pelea que has tenido has ganado? ¿Y perdido?" )
        let amigable62 = Preguntas.init(id: 62, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Cuál era tu canción favorita en tu infancia?" )
        let amigable63 = Preguntas.init(id: 63, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Has llevado la misma ropa por más de 3 días?")
        let amigable64 = Preguntas.init(id: 64, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\n¿Cuál es el video YouTube más divertido que has visto?")
        let amigable65 = Preguntas.init(id: 65, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Quién es el peor maestro que has tenido y por qué?")
        let amigable66 = Preguntas.init(id: 66, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Cuántos años tenías cuando diste tu primer beso?")
        let amigable67 = Preguntas.init(id: 67, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Qué harías si tu novio o novia acabara con su relación en este momento?")
        let amigable68 = Preguntas.init(id: 68, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Qué es lo más gracioso que te ha sucedido durante una cita romántica?" )
        let amigable69 = Preguntas.init(id: 69, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Si tuvieras que casarte con alguien que no te gusta, con quién te casarías?")
        let amigable70 = Preguntas.init(id: 70, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\nSi te encontraras en una isla desierta y tuvieras que elegir a un amigo para que te hiciera compañía, ¿a quién elegirías?")
        let amigable71 = Preguntas.init(id: 71, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Qué es lo más estúpido que has hecho en tu vida?")
        let amigable72 = Preguntas.init(id: 72, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:  "PREGUNTA AMIGABLE\n\nSi pudieras ser otra persona, ¿quién serías?¿Por qué?")
        let amigable73 = Preguntas.init(id: 72, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta: "PREGUNTA AMIGABLE\n\n¿Alguna vez has espiado a alguien?" )
        let amigable74 = Preguntas.init(id: 73, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\n¿Alguna vez has iniciado un rumor sobre alguien? ¿De qué se trataba?" )
        let amigable75 = Preguntas.init(id: 74, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"PREGUNTA AMIGABLE\n\nCuál ha sido la fiesta más salvaje a la que has ido?")
        let amigable76 = Preguntas.init(id: 75, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"¿PREGUNTA AMIGABLE\n\nCuál ha sido la broma más desagradable que has hecho en tu vida?" )
        //let amigable77 = Preguntas.init(id: 76, status: true, categoria: .Verdad, subcategoria:.Amigables, pregunta:"")
        
        // preguntas sexuales
        let s1 = Preguntas.init(id: 1, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n Alguna vez has tenido una relación de una noche? Si es así ¿Cuántas has tenido?")
        let s2 = Preguntas.init(id: 2, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Alguna vez has llorado durante un orgasmo?")
        let s3 = Preguntas.init(id: 3, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Alguna vez has interrumpido mientras tus padres estaban teniendo sexo?")
        let s4 = Preguntas.init(id: 4, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cual es tu posición sexual favorita?")
        let s5 = Preguntas.init(id: 5, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Alguna vez has sido suci@ en un coche?")
        let s6 = Preguntas.init(id: 6, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\nRecuerdas la primera vez que viste a un miembro del sexo opuesto(que no sean tus padres)desnudo?¿Qué te parecio?")
        let s7 = Preguntas.init(id: 7, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\nTe afeitas el vello púbico")
        let s8 = Preguntas.init(id: 8, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuantas veces durante el dia piensas en el sexo?")
        let s9 = Preguntas.init(id: 9, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Alguna vez has llegado al orgasmo con toda la ropa puesta?")
        let s10 = Preguntas.init(id: 10, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuando te comenzaste a masturbar?")
        let s11 = Preguntas.init(id: 11, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Recibes o das más?")
        let s12 = Preguntas.init(id: 12, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\nEntre todas las personas en esta sala, con qué persona lo hárias?")
        let s13 = Preguntas.init(id: 13, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Alguna vez has intimado a alguien?")
        let s14 = Preguntas.init(id: 14, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\nEl jugador a tu derecha debe contestar si ha tenido relaciones sexuales con alguien que conozcas, si es asi ¿quién era, cómo era? y darles una calificación.")
        let s15 = Preguntas.init(id: 15, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuál es tu mayor provocación sexual?")
        let s16 = Preguntas.init(id: 16, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuál es tu más profunda, más oscura fantasía?")
        let s17 = Preguntas.init(id: 17, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Alguna vez has usado lubricante?")
        let s18 = Preguntas.init(id: 18, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Con quién en el gruoo tendrías sexo y ¿ por qué tendrias sexo con él o ella?")
        let s19 = Preguntas.init(id: 19, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\nRedtube, Youporn o PornHub? ¿Cuál y porque..?")
        let s20 = Preguntas.init(id: 20, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Has tomado la virginidad de multiples personas?")
        let s21 = Preguntas.init(id: 21, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuál es el menor tiempo que has tardado en llegar a un orgasmo?")
        let s22 = Preguntas.init(id: 22, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cómo te sentirías si pillas a tu pareja dándose autoplacer?")
        let s23 = Preguntas.init(id: 23, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuál es tu fantasía sexual más deseada?")
        let s24 = Preguntas.init(id: 24, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Con cuántas personas te has acostado?")
        let s25 = Preguntas.init(id: 25, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\nDescribe el sueño más erótico que hayas tenido alguna vez")
        let s26 = Preguntas.init(id: 26, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuál ha sido tu mejor experiencia sexual?")
        let s27 = Preguntas.init(id: 27, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuál ha sido tu peor experiencia sexual?")
        let s28 = Preguntas.init(id: 28, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Has hecho un trío?")
        let s29 = Preguntas.init(id: 29, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Harías un trío?")
        let s30 = Preguntas.init(id: 30, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Has tenido alguna cita que haya salido mal?")
        let s31 = Preguntas.init(id: 31, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Qué es lo que más te excita?")
        let s32 = Preguntas.init(id: 32, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Te has acostado con alguien poco atractivo alguna vez?")
        let s33 = Preguntas.init(id: 33, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Alguna vez te has enrollado con varias personas en una misma noche?")
        let s34 = Preguntas.init(id: 34, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuál es tu sitio favorito para tener relaciones?")
        let s35 = Preguntas.init(id: 35, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Tienes algún fetiche inconfesable? ¿Cuál es?")
        let s36 = Preguntas.init(id: 36, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\nImagina que tienes el superpoder, durante una noche, de meter en tu cama a quien tú quieras. ¿Quién sería?")
        let s37 = Preguntas.init(id: 37, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Hay algún uniforme que te excite especialmente?")
        let s38 = Preguntas.init(id: 38, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Cuál es la cosa más embarazosa que has puesto en las redes sociales?")
        let s39 = Preguntas.init(id: 39, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "PREGUNTA SEXUAL\n\n¿Qué es lo más estúpido que le ha dicho a su pareja durante un momento íntimo?")
        //let s40 = Preguntas.init(id: 40, status: true, categoria: .Verdad, subcategoria:.Sexuales, pregunta:  "")
        
        // Preguntas prohibidas
        let ph1 = Preguntas.init(id: 1, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "BONUS\n\n  Redirije una pregunta de verdad cuando tu desees")
        let ph2 = Preguntas.init(id: 2, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "BONUS\n\n  Puedes redirigir una pregunta de la categoria 'verdad' en tus proximos 5 turnos")
        let ph3 = Preguntas.init(id: 3, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "CONDENA\n\n  Recibe un zape del jugador de la derecha cada vez que el considere que estas mintiendo")
        let ph4 = Preguntas.init(id: 4, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "CONDENA\n\n  Recibe un zape del jugador de la izquierda cada vez que el considere que estas mintiendo")
        let ph5 = Preguntas.init(id: 5, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "CONDENA\n\n  Recibe un zape del jugador de  al frente cada vez que el considere que estas mintiendo")
        let ph6 = Preguntas.init(id: 6, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "BONUS\n\n Menciona la cantidad exacta de dinero que llevas contigo si lo logras podrás librarte de una CONDENA")
        let ph7 = Preguntas.init(id: 7, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "BONUS\n\n  En este turno puedes librarte de una CONDENA solo si otro jugador te da un calcetin")
        let ph8 = Preguntas.init(id: 8, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "CONDENA\n\n  Recibe un zape del jugador de la derecha cada vez que el considere que estas mintiendo")
        let ph9 = Preguntas.init(id: 9, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "BONUS\n\n Puedes Filmar una Verdad antes de que el jugador la conteste")
        let ph10 = Preguntas.init(id: 10, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo si prefieren blanco 👍🏽 y bajen un dedo los que prefieren negro 👎🏽 .La minoria deberá aportar la moneda mas chica que tenga al centro")
        let ph11 = Preguntas.init(id: 11, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren No poder tener hijos y adoptar 2 👍🏽 y bajen un dedo los que prefieren tener 4 hijos propios 👎🏽 .La minoria deberá aportar la moneda mas chica que tenga al cent")
        let ph12 = Preguntas.init(id: 12, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren Encontrar el amor verdadero pero ser pobre 👍🏽 \n Bajen un dedo los que prefieren ser multimillonario pero no encontrar su alma gemela 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro")
        let ph13 = Preguntas.init(id: 13, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "BONUS\n\n Toma la mitad del dinero del Centro")
        let ph14 = Preguntas.init(id: 14, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren Que te cuenten que te han puesto el cuerno👍🏽 \n Bajen un dedo los que prefieren nunca enterarse 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al cent")
        let ph15 = Preguntas.init(id: 15, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren Tener 10 años toda tu vida👍🏽 \n Bajen un dedo los que prefieren tener 50 años toda su vida 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al cent")
        let ph16 = Preguntas.init(id: 16, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren que tu pareja vea un vídeo en el que le pones los cuernos 👍🏽 \n Bajen un dedo los que prefieren ver un vídeo en el que tu pareja te pone los cuernos 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro")
        let ph17 = Preguntas.init(id: 17, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren tener una noche de sexo con un desconocido 👍🏽 \n Bajen un dedo los que prefieren tener una noche de sexo con tu mejor amig@ 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro")
        let ph18 = Preguntas.init(id: 18, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren no volver a usar ropa intrior 👍🏽 \n Bajen un dedo los que prefieren solo poder usar ropa interior usada 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al cent")
        let ph19 = Preguntas.init(id: 19, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren no poder volver a besar a tu pareja 👍🏽 \n Bajen un dedo los que prefieren no poder volver a abrazar a tu pareja 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al cent")
        let ph20 = Preguntas.init(id: 20, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren ser listo pero muy feo 👍🏽 \n Bajen un dedo los que prefieren ser guapísimo pero muy tonto 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al cent")
        let ph21 = Preguntas.init(id: 21, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren sólo ser capaz de susurrar👍🏽 \n Bajen un dedo los que prefieren sólo ser capaz de gritar 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al cent")
        let ph22 = Preguntas.init(id: 22, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren vivir una vida del mejor sexo pero comiendo fatal 👍🏽 \n Bajen un dedo los que prefieren vivir una vida comiendo los manjares sero sin sexo 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro")
        let ph23 = Preguntas.init(id: 23, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren vivir eternamente y ver morir a tus seres queridos 👍🏽 \n Bajen un dedo los que prefieren morir antes de los 70 años pero vivir una vida perfecta 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro")
        let ph24 = Preguntas.init(id: 24, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren que no vaya nadie a tu boda 👍🏽 \n Bajen un dedo los que prefieren que no vaya nadie a tu funeral👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro")
        let ph25 = Preguntas.init(id: 25, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren perder 10000 pesos 👍🏽 \n Bajen un dedo los que prefieren que la persona que mas odias gane 1,000,000 de pesos 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro")
        let ph26 = Preguntas.init(id: 26, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "TODOS JUEGAN\n\n Levanten el dedo los que prefieren que te cachen  👍🏽 \n Bajen un dedo los que prefieren morir antes de los 70 años pero vivir una vida perfecta 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro")
//        let ph27 = Preguntas.init(id: 27, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph3")
//        let ph28 = Preguntas.init(id: 28, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph4")
//        let ph29 = Preguntas.init(id: 29, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph5")
//        let ph30 = Preguntas.init(id: 30, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph6")
//        let ph31 = Preguntas.init(id: 31, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph7")
//        let ph32 = Preguntas.init(id: 32, status: true, categoria: .Verdad, subcategoria:.Prohibidas, pregunta:  "ph8")
        
        
        //
        self.preguntas.append(p1)
        self.preguntas.append(p2)
        self.preguntas.append(p3)
        self.preguntas.append(p4)
        self.preguntas.append(p5)
        self.preguntas.append(p6)
        self.preguntas.append(p7)
        self.preguntas.append(p8)
        self.preguntas.append(p9)
        self.preguntas.append(p10)
        self.preguntas.append(p11)
        self.preguntas.append(p12)
        self.preguntas.append(p13)
        self.preguntas.append(p14)
        self.preguntas.append(p15)
        self.preguntas.append(p16)
        self.preguntas.append(p17)
        self.preguntas.append(p18)
        self.preguntas.append(p19)
        self.preguntas.append(p20)
        self.preguntas.append(p21)
        self.preguntas.append(p22)
        self.preguntas.append(p23)
        self.preguntas.append(p24)
        self.preguntas.append(p25)
        self.preguntas.append(p26)
        self.preguntas.append(p27)
        self.preguntas.append(p28)
        self.preguntas.append(p29)
        self.preguntas.append(p30)
        self.preguntas.append(p31)
        self.preguntas.append(p32)
        self.preguntas.append(p33)
        self.preguntas.append(p34)
        self.preguntas.append(p35)
        self.preguntas.append(p36)
        self.preguntas.append(p37)
        self.preguntas.append(p38)
        self.preguntas.append(p39)
        self.preguntas.append(p40)
        self.preguntas.append(p41)
        self.preguntas.append(p42)
        self.preguntas.append(p43)
        self.preguntas.append(p44)
        self.preguntas.append(p45)
        self.preguntas.append(p46)
        self.preguntas.append(p47)
        self.preguntas.append(p48)
        self.preguntas.append(p49)
        self.preguntas.append(p50)
        self.preguntas.append(p51)
        self.preguntas.append(p52)
        self.preguntas.append(p53)
        self.preguntas.append(p54)
        self.preguntas.append(p55)
        self.preguntas.append(p56)
        self.preguntas.append(p57)
        self.preguntas.append(p58)
        self.preguntas.append(p59)
        self.preguntas.append(p60)
        self.preguntas.append(p61)
        self.preguntas.append(p62)
        self.preguntas.append(p63)
        self.preguntas.append(p63)
        self.preguntas.append(p64)
        self.preguntas.append(p65)
        self.preguntas.append(p66)
        self.preguntas.append(p67)
        self.preguntas.append(p68)
        self.preguntas.append(p69)
        self.preguntas.append(p70)
        self.preguntas.append(p71)
        self.preguntas.append(p72)
        self.preguntas.append(p73)
        self.preguntas.append(p74)
        self.preguntas.append(p75)
        self.preguntas.append(p76)
        self.preguntas.append(p77)
        self.preguntas.append(p78)
        self.preguntas.append(p79)
        self.preguntas.append(p80)
        self.preguntas.append(p81)
        self.preguntas.append(p82)
        self.preguntas.append(p83)
        self.preguntas.append(p84)
        self.preguntas.append(p85)
        self.preguntas.append(p86)
        self.preguntas.append(p87)
        self.preguntas.append(p88)
        self.preguntas.append(p89)
        self.preguntas.append(p90)
        self.preguntas.append(p91)
        self.preguntas.append(p92)
        self.preguntas.append(p93)
        self.preguntas.append(p94)
        self.preguntas.append(p95)
        self.preguntas.append(p96)
        self.preguntas.append(p97)
        self.preguntas.append(p98)
        self.preguntas.append(p99)
        self.preguntas.append(p100)
        self.preguntas.append(p101)
        self.preguntas.append(p102)
        self.preguntas.append(p103)
        self.preguntas.append(p104)
        self.preguntas.append(p105)
        self.preguntas.append(p106)
        self.preguntas.append(p107)
        self.preguntas.append(p108)
        self.preguntas.append(p109)
        self.preguntas.append(p110)
        self.preguntas.append(p111)
        self.preguntas.append(p112)
        self.preguntas.append(p113)
        self.preguntas.append(p114)
        self.preguntas.append(p115)
        self.preguntas.append(p116)
        self.preguntas.append(p117)
        self.preguntas.append(p118)
        self.preguntas.append(p119)
        self.preguntas.append(p120)
        self.preguntas.append(p121)
        self.preguntas.append(p122)
        self.preguntas.append(p123)
        self.preguntas.append(p124)
        self.preguntas.append(p125)
        self.preguntas.append(p126)
        self.preguntas.append(p127)
        
        //
        self.preguntas.append(amigable1)
        self.preguntas.append(amigable2)
        self.preguntas.append(amigable3)
        self.preguntas.append(amigable4)
        self.preguntas.append(amigable5)
        self.preguntas.append(amigable6)
        self.preguntas.append(amigable7)
        self.preguntas.append(amigable8)
        self.preguntas.append(amigable9)
        self.preguntas.append(amigable10)
        self.preguntas.append(amigable11)
        self.preguntas.append(amigable12)
        self.preguntas.append(amigable13)
        self.preguntas.append(amigable14)
        self.preguntas.append(amigable15)
        self.preguntas.append(amigable16)
        self.preguntas.append(amigable17)
        self.preguntas.append(amigable18)
        self.preguntas.append(amigable19)
        self.preguntas.append(amigable20)
        self.preguntas.append(amigable21)
        self.preguntas.append(amigable22)
        self.preguntas.append(amigable23)
        self.preguntas.append(amigable24)
        self.preguntas.append(amigable25)
        self.preguntas.append(amigable26)
        self.preguntas.append(amigable27)
        self.preguntas.append(amigable28)
        self.preguntas.append(amigable29)
        self.preguntas.append(amigable30)
        self.preguntas.append(amigable31)
        self.preguntas.append(amigable32)
        self.preguntas.append(amigable33)
        self.preguntas.append(amigable34)
        self.preguntas.append(amigable35)
        self.preguntas.append(amigable36)
        self.preguntas.append(amigable37)
        self.preguntas.append(amigable38)
        self.preguntas.append(amigable39)
        self.preguntas.append(amigable40)
        self.preguntas.append(amigable41)
        self.preguntas.append(amigable42)
        self.preguntas.append(amigable43)
        self.preguntas.append(amigable44)
        self.preguntas.append(amigable45)
        self.preguntas.append(amigable46)
        self.preguntas.append(amigable47)
        self.preguntas.append(amigable48)
        self.preguntas.append(amigable49)
        self.preguntas.append(amigable50)
        self.preguntas.append(amigable51)
        self.preguntas.append(amigable52)
        self.preguntas.append(amigable53)
        self.preguntas.append(amigable54)
        self.preguntas.append(amigable55)
        self.preguntas.append(amigable56)
        self.preguntas.append(amigable57)
        self.preguntas.append(amigable58)
        self.preguntas.append(amigable59)
        self.preguntas.append(amigable60)
        self.preguntas.append(amigable61)
        self.preguntas.append(amigable62)
        self.preguntas.append(amigable63)
        self.preguntas.append(amigable64)
        self.preguntas.append(amigable65)
        self.preguntas.append(amigable66)
        self.preguntas.append(amigable67)
        self.preguntas.append(amigable68)
        self.preguntas.append(amigable69)
        self.preguntas.append(amigable70)
        self.preguntas.append(amigable71)
        self.preguntas.append(amigable72)
        self.preguntas.append(amigable73)
        self.preguntas.append(amigable74)
        self.preguntas.append(amigable75)
        self.preguntas.append(amigable76)
        self.preguntas.append(amigable77)
        //
        self.preguntas.append(s1)
        self.preguntas.append(s2)
        self.preguntas.append(s3)
        self.preguntas.append(s4)
        self.preguntas.append(s5)
        self.preguntas.append(s6)
        self.preguntas.append(s7)
        self.preguntas.append(s8)
        self.preguntas.append(s9)
        self.preguntas.append(s10)
        self.preguntas.append(s11)
        self.preguntas.append(s12)
        self.preguntas.append(s13)
        self.preguntas.append(s14)
        self.preguntas.append(s15)
        self.preguntas.append(s16)
        self.preguntas.append(s17)
        self.preguntas.append(s18)
        self.preguntas.append(s19)
        self.preguntas.append(s20)
        self.preguntas.append(s21)
        self.preguntas.append(s22)
        self.preguntas.append(s23)
        self.preguntas.append(s24)
        self.preguntas.append(s25)
        self.preguntas.append(s26)
        self.preguntas.append(s27)
        self.preguntas.append(s28)
        self.preguntas.append(s29)
        self.preguntas.append(s30)
        self.preguntas.append(s31)
        self.preguntas.append(s32)
        self.preguntas.append(s33)
        self.preguntas.append(s34)
        self.preguntas.append(s35)
        self.preguntas.append(s36)
        self.preguntas.append(s37)
        self.preguntas.append(s38)
        self.preguntas.append(s39)
        self.preguntas.append(s40)
        //
        self.preguntas.append(ph1)
        self.preguntas.append(ph2)
        self.preguntas.append(ph3)
        self.preguntas.append(ph4)
        self.preguntas.append(ph5)
        self.preguntas.append(ph6)
        self.preguntas.append(ph7)
        self.preguntas.append(ph8)
        self.preguntas.append(ph9)
        self.preguntas.append(ph10)
        self.preguntas.append(ph11)
        self.preguntas.append(ph12)
        self.preguntas.append(ph13)
        self.preguntas.append(ph14)
        self.preguntas.append(ph15)
        self.preguntas.append(ph16)
        self.preguntas.append(ph17)
        self.preguntas.append(ph18)
        self.preguntas.append(ph19)
        self.preguntas.append(ph20)
        self.preguntas.append(ph21)
        self.preguntas.append(ph22)
        self.preguntas.append(ph23)
        self.preguntas.append(ph24)
        self.preguntas.append(ph25)
        self.preguntas.append(ph26)
        self.preguntas.append(ph27)
        self.preguntas.append(ph28)
        self.preguntas.append(ph29)
        self.preguntas.append(ph30)
        self.preguntas.append(ph31)
        self.preguntas.append(ph32)
        
        
        
        
    }
    
    func changeStatusVerdad(status : Bool) -> Void {
        for pregunta in preguntas{
            if (pregunta.subcategoria == .Inocentes){
                pregunta.status = status
            }
            
        }
        
    }
    func changeStatusAmigables(status : Bool) -> Void {
        for pregunta in preguntas{
            if (pregunta.subcategoria == .Amigables){
                pregunta.status = status
            }
            
        }
        
    }
    
    func changeStatusSexuales(status : Bool) -> Void {
        for pregunta in preguntas{
            if (pregunta.subcategoria == .Sexuales){
                pregunta.status = status
            }
            
        }
        
    }
    
    func changeStatusProhibidas(status : Bool) -> Void {
        for pregunta in preguntas{
            if (pregunta.subcategoria == .Prohibidas){
                pregunta.status = status
            }
            
        }
        
    }
    
}
