//
//  StringVerdadReto.swift
//  True Dare or shots
//
//  Created by Diego on 20/09/18.
//  Copyright © 2018 diego. All rights reserved.
//

import Foundation

//arreglos verdad
// arrayverdad1
// arrayverdad2
// arrayverdad3
// arrayverdad4



//Inocentes
let arrayverdad1 = [
    "1.-Si fueras un alimento ¿Qué serías y ¿cómo otras personas te comerían?",
    "2.-¿Con qué tipo de persona te gustaría casarte algún dia?",
    "3.-¿Cuál es tu talento secreto?",
    "4.-¿Si tuvieras la oportunidad de volver a nacer como alguien más en este cuarto,¿quién sería?¿Por qué?",
    "5.-Si le va a dar consejo de (no hagas lo que yo hice) a una persona mas joven ¿qué sería?",
    "6.-¿Cuál es tu idea de una cita perfecta?",
    "7.-¿Alguna vez has besado al hermano o hermana de un amigo?",
    "8.-¿Cuándo has amado a alguien que no te haya amado de vuelta?",
    "9.-¿Cuando tuviste tu primer beso y cómo fue?",
    "10.-¿De que tienes miedo?",
    "11.-¿Cuál es tu mayor secreto?",
    "12.-Si pudieras cambiar una cosa en tu cuerpo, ¿cuál sería?",
    "13.- Si tuvieras la oportunidad de salir en una cita con alguien que está presente, ¿quién sería?",
    "14.-Si pudieras tener una relación con un/a famoso/a, ¿quién sería",
    "15.-¿Cuál ha sido el peor día de tu vida?",
    "16.-¿Qué es lo más loco que has hecho por un chico o una chica?",
    "17.-¿Te arrepientes de algo en esta vida?",
    "18.- ¿Qué es lo más estúpido que has hecho nunca?",
    "19.-¿Qué es lo que la mayoría de gente piensa de ti y es totalmente falso?",
    "20.-¿Cuál es la cosa más infantil que todavía haces?",
    "21.-¿Dejarías a tu pareja si te ofrecieran 1 millón de euros?",
    "22.-¿Cómo fue tu primer beso?",
    "23.-¿Te gusta tu trabajo/escuela? ¿Por qué?",
    "24.-¿Qué es lo más loco que has hecho en la vida?",
    "25.-¿Has mentido a alguien para no herir sus sentimientos?",
    "26.- ¿Qué cualidad física te hace caer rendido/a a los pies de alguien?",
    "27.-¿Cuál es el sitio más extraño en que has conocido a una persona con la que terminaste saliendo?",
    "28.-¿Qué es lo más extraño que has buscado en internet?",
    "29.-¿Cuál es la cosa más infantil que todavía haces?",
    "30.-¿Qué no has contado nunca a nadie?",
    "31.-¿Cuándo ha sido el momento más inapropiado de tu vida en que te has tirado un pedo?",
    "32.-Si tuvieras un control remoto que funciona sobre cualquier cosa, ¿qué controlaría?",
    "33.-¿Cuál es el hábito más repugnante que tienes?",
    "34.-¿Qué quieres que tus padres nunca sepan?",
    "35.-¿A quién salvarías si viene un meteorito y solo puedes salvar a una persona?",
    "36.-¿Cuál es tu estrategia para conquistar a una mujer/hombre?",
    "37.-¿Qué es lo más loco que has hecho sin que tus padres lo sepan?",
    "38.-¿Qué harías si tus padres te dejaran en casa durante una semana entera?",
    "39.-¿Alguna vez te gustó uno de tus profesores en la escuela?",
    "40.-¿Cuál es la foto más vergonzosa de ti?",
    "41.-¿Qué cosa mala has hecho que nadie descubrió?",
    "42.-¿Cuál es la cosa más tonta a la que tienes un apego emocional?",
    "43.-¿Cuál es tu miedo más oscuro?",
    "44.-¿Alguna vez has mentido acerca de estar enfermo para que puedas quedarte en casa y no ir al trabajo o a la escuela?",
    "45.-¿Cuál es el lugar más extraño en el que has orinado?",
    "46.-¿Alguna vez te has hecho caca en los pantalones desde que eras un niño?",
    "47.-¿Cuándo fue la última vez que te orinaste en la cama?",
    "48.-Si pudieras volver a hacer una cosa que hiciste cuando eras un niño, ¿cuál sería?",
    "49.-¿Cuál es la cosa más grosera que ha salido de tu cuerpo?",
    "50.-¿Alguna vez te has tirado un pedo fuerte en clase?",
    "51.-¿Con qué frecuencia lavas tu ropa interior?",
    "52.-¿Alguna vez has probado la cera del oído?",
    "53.-¿Alguna vez le enviaste un texto inapropiado a tu mamá o papá por accidente?",
    "54.-¿Has llegado a olfatear tu ropa interior para saber si está limpia?",
    "55.-¿Qué es lo más desagradable que has hecho en lugar público?",
    "56.-¿Qué harías si supieras que el mundo acabará mañana?",
    "57.-¿Qué has hecho alguna vez y no has contado a nadie?",
    "58.-¿Cuándo fue la última vez que cantaste y bailaste solo?",
    "59.-¿Quién tiene los ojos más hermosos de todas las personas presentes?",
    "60.-¿A qué persona famosa besarías?",
    "61.-¿ A quién llevarías contigo si te quedarás naufrago durante 3 días en una isla?",
    "62.-¿Qué harías si fueras invisible por un día?",
    "63.-¿Cuánto es el tiempo máximo que has pasado sin darte un baño?",
    "64.-¿Quién es la persona que más sabe de ti y qué tipo de secretos sobre tu vida guarda?",
    "65.-¿De qué color es tu ropa interior?",
    "66.-¿Cuál es el lugar más extraño en el que has tenido que ir al baño?",
    "67.-¿Cómo sería tu primera cita perfecta?",
    "68.-¿Cuál crees que es la parte más atractiva de tu cuerpo?",
    "69.-¿Qué es lo primero que le miras a una mujer o un hombre cuando lo conoces?",
    "70.-¿Alguna vez hiciste trampa en la escuela para pasar un examen?",
    "71.-¿Qué estarías dispuesto a hacer por un millón de dólares?",
    "72.-¿Te has enamorado de alguien alguna vez y no se lo has contado?",
    "73.-¿Cuál es tu fantasía más deseada?",
    "74.-¿Cuál fue el momento más embarazoso de tu vida?",
    "75.-¿Cuál es la cosa más embarazosa que tus padres te han pillado haciendo?",
    "76.-Cuál es la comida más exótica que has comido",
    "77.-¿Qué te gustaría cambiar de tu cuerpo?",
    "78.-¿Quién es tu persona favorita y por qué?",
    "79.-¿Qué película elegirías si pudieras convertirla en tu vida?",
    "80.-¿Cuál es tu película favorita de Disney y por qué?",
    "81.-¿Qué harías con un millón de dólares si alguna vez ganaras la lotería?",
    "82.-Danos una lista de 10 artículos o cosas que compraste y nunca utilizaste o lamentaste comprar",
    "83.-¿Cuál ha sido tu mayor humillación?",
    "84.-¿Qué es lo más loco que te ha pasado en un centro comercial?",
    "85.-¿Cuál es la broma más cruel que le has gastado a alguien?",
    "86.-¿Cuál es la peor mentira que le has dicho a tus padres?",
    "87.-¿Cuál es la cosa que más te molesta que hace tu mamá?",
    "88.-¿Cuál es la cosa que más te molesta de tu papa?",
    "89.-¿Cuál es la historia más divertida que tus abuelos te han contado?",
    "90.-¿Cuál era tu canción favorita en tu infancia?",
    "91.-¿Cómo es la casa de tus sueños?",
    "92.-¿Has llevado la misma ropa por más de 3 días?",
    "93.-¿Qué animal serías?",
    "94.-¿Qué dinosaurio serías?",
    "95.-¿Qué supervillano serías?",
    "96.-¿Con qué celebridad estás obsesionado?",
    "97.-¿Cuál es el video YouTube más divertido que has visto?",
    "98.-¿Quién es el peor maestro que has tenido y por qué?",
    "99.-¿Cuál es tu equipo deportivo favorito?",
    "100.-¿Cuál es tu canción favorita en este momento?",
    "101.-¿Podrías pasar dos meses sin hablar con tus amigos?",
    "102.-¿Podrías pasar dos meses sin tu teléfono?",
    "103.-¿Podrías pasar dos meses sin ver televisión?",
    "104.-¿Podrías pasar dos meses sin conectarte a las redes sociales?",
    "105.-¿Qué prejuicio albergas secretamente?",
    "106.-¿Si pudieras salir con algún famoso con quién sería?",
    "107.-¿Qué es lo más gracioso que te ha sucedido durante una cita romántica?",
    "108.-¿Qué harías si te encontraras mucho dinero en la calle?",
    "109.-¿En qué condiciones le mentirías a un amigo?",
    "110.-¿Cuál creerías que puede ser una pregunta bastante incómoda?",
    "111.-¿Alguna vez has robado algo? ¿Qué robaste y por qué lo hiciste?",
    "112.-¿Si no estuvieras aquí, que estarías haciendo en este momento?",
    "113.-¿Si pudieras hacer lo que quisieras, cuál sería tu trabajo soñado?",
    "114.-¿Qué quieres hacer durante los próximos años?",
    "115.-Si pudieras ser otra persona, ¿quién serías?",
    "116.-¿Qué te gustaría inventar?",
    "117.-Si pudieras nacer de nuevo, ¿dónde te gustaría nacer? ¿Quién te gustaría ser?",
    "118.-¿Alguna vez has actuado como un loco en un lugar público?",
    "119.-¿Alguna vez has pretendido ser quien no eres para obtener algún beneficio?",
    "120.-¿Qué harías si pudieras viajar en el tiempo?",
    "121.-¿Alguna vez has espiado a alguien?",
    "122.-¿Qué es lo que más te molesta?",
    "123.-¿Qué harías si ganaras la lotería?",
    "124.-¿Cuál ha sido el piropo más extraño que te han dicho?",
    "125.-¿Cuál ha sido el peor rumor que has compartido? (sabiendo que no era cierto)",
    "126.-¿Cuál ha sido el evento más traumático de tu vida?",
    "127.-¿Cuál ha sido la peor fiesta a la que has ido?"]


//Amigables
let arrayverdad2 = [
    "1.-¿De que carecteristica tuya eres demasiado consciente?",
     "2.-¿Cuando fue la primera vez que fumaste?",
     "3.-¿Has fallado en seducir a alguien? Si es así cuantas veces?",
     "4.-¿Romperías la relación de una pareja si eso te llevase a salir con la persona de tus sueños?",
     "5.-¿Qué tipo de borracho eres: feliz,social,difundes el amor,malvado, sexual,calmado,astuto",
     "6.-¿Cuanto dinero ganas?",
     "7.-Alguna vez has engañado a tu novi@?",
     "8.-¿Cuantas veces durante el dia piensas en el sexo?",
     "9.-Si fueras un alimento ¿Qué serías y cómo otras personas te comerían?",
     "10.-Si no eres gay, que persona presente sería más probable que te volviera gay",
     "11.-¿Cuál es el sueño mas sucio que has tenido? Describe con detalle",
     "12.-¿Si tuvieras que matar a alguien ¿Quién sería?",
     "13.-¿Cuál es tu talento secreto?",
     "14.-¿Si tuvieras la oportunidad de volver a nacer como alguien más en este cuarto,¿quién sería?¿Por qué?",
     "15.-Entre todas las personas en esta sala, con qué persona lo hárias?",
     "16.-¿Cual es la cosa más loca que has hecho desnudo?",
     "17.-Redtube, Youporn o PornHub? ¿Cuál y porque..?",
     "18.-¿Alguna vez has besado a alguien del mismo sexo? ¿Quien?",
     "19.-¿Alguna vez has acosado a alguien? Si lo has ¿Quién fue?",
     "20.-¿Cuando tuviste tu primer beso y cómo fue?",
     "21.- Si tuvieras la oportunidad de salir en una cita con alguien que está presente, ¿quién sería?",
     "22.-Si pudieras tener sexo con un/a famoso/a, ¿quién sería",
     "23.- ¿Te gusta alguien ahora mismo?",
     "24.-¿Has sentido atracción por algún amigo/a de tu pareja actual o anteriores?",
     "25.-¿Has confesado un secreto a alguien en confianza y éste lo ha contado? ¿Qué era?",
     "26.-¿Has mentido a alguien para no herir sus sentimientos?",
     "27.-¿Tus padres te han pillado dándote autoplacer?",
     "28.-¿Cuál fue el motivo de tu última ruptura de pareja?",
     "29.-¿Alguna vez has sido infiel?",
     "30.-Si ves accidentalmente una una persona del sexo opuesto desnuda y no lo sabe, ¿seguirías mirando?",
     "31.-¿Has tenido conversaciones subidas de tono por chat o WhatsApp?",
     "32.-¿Qué edad tenía la persona más mayor de las que has tenido relaciones?",
     "33.-¿Qué edad tenía la persona más joven de las que has tenido relaciones?",
     "34.-¿Sientes o has sentido atracción física por algún familiar lejano?",
     "35.-Si algún día te casas, ¿dónde te gustaría que fuera la ceremonia?",
     "36.-¿Cuál es el hábito más repugnante que tienes?",
     "37.-¿Qué quieres que tus padres nunca sepan?",
     "38.-¿Qué harías si tus padres te dejaran en casa durante una semana entera?",
     "39.-¿Cuál es la cosa más cara que has robado?",
     "40.-¿Quién es la persona que más has lamentado besar?",
     "41.-¿Quién tiene el mejor trasero de todos los que estamos aquí?",
     "42.-¿Cuál de los jugadores de este grupo tiene una boca más sensual?",
     "43.-¿Cuál es la parte del cuerpo que encuentra más atractiva en una persona del otro (o mismo) género?",
     "44.-¿Cuál de las personas dentro de este grupo crees que ha mejorado su apariencia física?",
     "45.-¿Crees que alguna de las personas que se encuentran aquí tiene una pareja que no le conviene? ¿Quién? ¿Por qué?",
     "46.-¿Con quién saldrías de aquí en una cita?",
     "47.-¿Alguna vez has orinado en una piscina?",
     "48.-¿Qué es lo primero que le miras a una mujer o un hombre cuando lo conoces?",
     "49.-¿Alguna vez hiciste trampa en la escuela para pasar un examen?",
     "50.-¿Cómo fue tu primer beso?",
     "51.-¿Qué estarías dispuesto a hacer por un millón de dólares?",
     "52.-¿Cuál fue el encuentro romántico más incómodo que tuviste?",
     "53.-¿Has hecho cosas borracho que al día siguiente no recuerdes?",
     "54.-¿Qué es lo más loco que has hecho mientras estabas borracho?",
     "55.-¿Quién es la persona más sexy aquí?",
     "56.-En qué país te gustaría vivir si tuvieras la oportunidad",
     "57.-¿Alguna vez has contado una mentira durante un juego de verdad o reto? ¿Qué fue y por qué?",
     "58.-¿Cuál es la broma más cruel que le has gastado a alguien?",
     "59.-¿Cuál es la cosa más embarazosa que has puesto en las redes sociales?",
    "60.-¿Cuál es la peor mentira que le has dicho a tus padres?",
    "61.-¿En qué pelea que has tenido has ganado? ¿Y perdido?",
    "62.-¿Cuál era tu canción favorita en tu infancia?",
    "63.-¿Has llevado la misma ropa por más de 3 días?",
    "64.-¿Cuál es el video YouTube más divertido que has visto?",
    "65.-¿Quién es el peor maestro que has tenido y por qué?",
    "66.-¿Cuántos años tenías cuando diste tu primer beso?",
    "67.-¿Qué harías si tu novio o novia acabara con su relación en este momento?",
    "68.-¿Qué es lo más gracioso que te ha sucedido durante una cita romántica?",
    "69.-¿Si tuvieras que casarte con alguien que no te gusta, con quién te casarías?",
    "70.-Si te encontraras en una isla desierta y tuvieras que elegir a un amigo para que te hiciera compañía, ¿a quién elegirías?",
    "71.-¿Qué es lo más estúpido que has hecho en tu vida?",
    "72.-Si pudieras ser otra persona, ¿quién serías?¿Por qué?",
    "73.-¿Alguna vez has espiado a alguien?",
    "74.-¿Alguna vez has iniciado un rumor sobre alguien? ¿De qué se trataba?",
    "75.-Cuál ha sido la fiesta más salvaje a la que has ido?",
    "76.-¿Cuál ha sido la broma más desagradable que has hecho en tu vida?",
    "77.-",
    "78.-",
    "79.-",
    "80.-",
    "81.-",
    "82.-",
    "83.-",
    "84.-",
    "85.-",
    "86.-",
    "87.-",
    "88.-",
    "89.-",
    "90.-",
    "91.-",
    "92.-",
    "93.-",
    "94.-",
    "95.-",
    "96.-",
    "97.-",
    "98.-",
    "99.-",
    "100.-",
    "101.-",
    "102.-",
    "103.-",
    "104.-",
    "105.-",
    "106.-",
    "107.-",
    "108.-",
    "109.-",
    "110.-",
    "111.-",
    "112.-",
    "113.-",
    "114.-",
    "115.-",
    "116.-",
    "117.-",
    "118.-",
    "119.-",
    "120.-",
    "121.-",
    "122.-",
    "123.-",
    "124.-",
    "125.-",
    "126.-"]


//Sexuales
let arrayverdad3 = [
    "1.-Alguna vez has tenido una relación de una noche? Si es así ¿Cuántas has tenido?",
    "2.-¿Alguna vez has llorado durante un orgasmo?",
    "3.-¿Alguna vez has interrumpido mientras tus padres estaban teniendo sexo?",
    "4.-¿Cual es tu posición sexual favorita?",
    "5.-¿Alguna vez has sido suci@ en un coche?",
    "6.-Recuerdas la primera vez que viste a un miembro del sexo opuesto(que no sean tus padres)desnudo?¿Qué te parecio?",
    "7.-Te afeitas el vello púbico",
    "8.-¿Cuantas veces durante el dia piensas en el sexo?",
    "9.-¿Alguna vez has llegado al orgasmo con toda la ropa puesta?",
    "10.-¿Cuando te comenzaste a masturbar?",
    "11.-¿Recibes o das más?",
    "12.-Entre todas las personas en esta sala, con qué persona lo hárias?",
    "13.-¿Alguna vez has intimado a alguien?",
    "14.-El jugador a tu derecha debe contestar si ha tenido relaciones sexuales con alguien que conozcas, si es asi ¿quién era, cómo era? y darles una calificación.",
    "15.-¿Cuál es tu mayor provocación sexual?",
    "16.-¿Cuál es tu más profunda, más oscura fantasía?",
    "17.-¿Alguna vez has usado lubricante?",
    "18.-¿Con quién en el gruoo tendrías sexo y ¿ por qué tendrias sexo con él o ella?",
    "19.-Redtube, Youporn o PornHub? ¿Cuál y porque..?",
    "20.-¿Has tomado la virginidad de multiples personas?",
    "21.-¿Cuál es el menor tiempo que has tardado en llegar a un orgasmo?",
    "22.-¿Cómo te sentirías si pillas a tu pareja dándose autoplacer?",
    "23.-¿Cuál es tu fantasía sexual más deseada?",
    "24.-¿Con cuántas personas te has acostado?",
    "25.-Describe el sueño más erótico que hayas tenido alguna vez",
    "26.-¿Cuál ha sido tu mejor experiencia sexual?",
    "27.- ¿Cuál ha sido tu peor experiencia sexual?",
    "28.-¿Has hecho un trío?",
    "29.-¿Harías un trío?",
    "30.-¿Has tenido alguna cita que haya salido mal?",
    "31.-¿Qué es lo que más te excita?",
    "32.-¿Te has acostado con alguien poco atractivo alguna vez?",
    "33.-¿Alguna vez te has enrollado con varias personas en una misma noche?",
    "34.- ¿Cuál es tu sitio favorito para tener relaciones?",
    "35.- ¿Tienes algún fetiche inconfesable? ¿Cuál es?",
    "36.-Imagina que tienes el superpoder, durante una noche, de meter en tu cama a quien tú quieras. ¿Quién sería?",
    "37.-¿Hay algún uniforme que te excite especialmente?",
    "38.-¿Cuál es la cosa más embarazosa que has puesto en las redes sociales?",
    "39.-¿Qué es lo más estúpido que le ha dicho a su pareja durante un momento íntimo?",
    "40.-",
    "41.-",
    "42.-",
    "43.-",
    "44.-",
    "45.-",
    "46.-",
    "47.-",
    "48.-",
    "49.-",
    "50.-",
    "51.-",
    "52.-",
    "53.-",
    "54.-",
    "55.-",
    "56.-",
    "57.-",
    "58.-",
    "59.-",
    "60.-",
    "61.-",
    "62.-",
    "63.-",
    "64.-",
    "65.-",
    "66.-",
    "67.-",
    "68.-",
    "69.-",
    "70.-",
    "71.-",
    "72.-",
    "73.-",
    "74.-",
    "75.-",
    "76.-"]



//Prohibidas
let arrayverdad4 = [
    "BONUS\n\n  Redirije una pregunta de verdad cuando tu desees",
    "BONUS\n\n  Puedes redirigir una pregunta de la categoria 'verdad' en tus proximos 5 turnos",
    "CONDENA\n\n  Recibe un zape del jugador de la derecha cada vez que el considere que estas mintiendo",
    "CONDENA\n\n  Recibe un zape del jugador de la izquierda cada vez que el considere que estas mintiendo",
    "CONDENA\n\n  Recibe un zape del jugador de  al frente cada vez que el considere que estas mintiendo",
    "BONUS\n\n Menciona la cantidad exacta de dinero que llevas contigo si lo logras podrás librarte de una CONDENA",
    "BONUS\n\n  En este turno puedes librarte de una CONDENA solo si otro jugador te da un calcetin ",
    "CONDENA\n\n  Recibe un zape del jugador de la derecha cada vez que el considere que estas mintiendo",
    "BONUS\n\n Puedes Filmar una Verdad antes de que el jugador la conteste",
    "TODOS JUEGAN\n\n Levanten el dedo si prefieren blanco 👍🏽 y bajen un dedo los que prefieren negro 👎🏽 .La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren No poder tener hijos y adoptar 2 👍🏽 y bajen un dedo los que prefieren tener 4 hijos propios 👎🏽 .La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren Encontrar el amor verdadero pero ser pobre 👍🏽 \n Bajen un dedo los que prefieren ser multimillonario pero no encontrar su alma gemela 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "BONUS\n\n Toma la mitad del dinero del Centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren Que te cuenten que te han puesto el cuerno👍🏽 \n Bajen un dedo los que prefieren nunca enterarse 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren Tener 10 años toda tu vida👍🏽 \n Bajen un dedo los que prefieren tener 50 años toda su vida 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren que tu pareja vea un vídeo en el que le pones los cuernos 👍🏽 \n Bajen un dedo los que prefieren ver un vídeo en el que tu pareja te pone los cuernos 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren tener una noche de sexo con un desconocido 👍🏽 \n Bajen un dedo los que prefieren tener una noche de sexo con tu mejor amig@ 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren no volver a usar ropa intrior 👍🏽 \n Bajen un dedo los que prefieren solo poder usar ropa interior usada 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren no poder volver a besar a tu pareja 👍🏽 \n Bajen un dedo los que prefieren no poder volver a abrazar a tu pareja 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren ser listo pero muy feo 👍🏽 \n Bajen un dedo los que prefieren ser guapísimo pero muy tonto 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren sólo ser capaz de susurrar👍🏽 \n Bajen un dedo los que prefieren sólo ser capaz de gritar 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren vivir una vida del mejor sexo pero comiendo fatal 👍🏽 \n Bajen un dedo los que prefieren vivir una vida comiendo los manjares sero sin sexo 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren vivir eternamente y ver morir a tus seres queridos 👍🏽 \n Bajen un dedo los que prefieren morir antes de los 70 años pero vivir una vida perfecta 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren que no vaya nadie a tu boda 👍🏽 \n Bajen un dedo los que prefieren que no vaya nadie a tu funeral👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren perder 10000 varos 👍🏽 \n Bajen un dedo los que prefieren que la persona que mas odias gane 1,000,000 de pesos 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "TODOS JUEGAN\n\n Levanten el dedo los que prefieren que te cachen  👍🏽 \n Bajen un dedo los que prefieren morir antes de los 70 años pero vivir una vida perfecta 👎🏽. \n La minoria deberá aportar la moneda mas chica que tenga al centro",
    "27.-",
    "28.-",
    "29.-",
    "30.-",
    "31.-",
    "32.-",
    "33.-",
    "34.-",
    "35.-",
    "36.-",
    "37.-",
    "38.-",
    "39.-",
    "40.-",
    "41.-",
    "42.-",
    "43.-",
    "44.-",
    "45.-",
    "46.-",
    "47.-",
    "48.-",
    "49.-",
    "50.-",
    "51.-",
    "52.-",
    "53.-",
    "54.-",
    "55.-",
    "56.-",
    "57.-",
    "58.-",
    "59.-",
    "60.-",
    "61.-",
    "62.-",
    "63.-",
    "64.-",
    "65.-",
    "66.-",
    "67.-",
    "68.-",
    "69.-",
    "70.-",
    "71.-",
    "72.-",
    "73.-",
    "74.-",
    "75.-",
    "76.-"]


